import{Coffee,Download,Pencil,Plus,Search,X}from"lucide-react";
import{useCallback,useEffect,useMemo,useState}from"react";
import{BreakService,formatBreakDuration,type BreakRecord,type BreakType}from"../../services/breakService";
import{notifyError,notifySuccess}from"../../components/common/CrmNotifications";
import{useAuth}from"../auth/AuthProvider";
import{BreakWidget}from"./BreakWidget";

const localInput=(value:string|null)=>value?new Date(value).toLocaleString("sv-SE",{timeZone:"Asia/Kathmandu"}).slice(0,16):"";
const isoFromNepal=(value:string)=>value?new Date(`${value}:00+05:45`).toISOString():undefined;
export function BreakManagementWorkspace(){
 const{hasPermission}=useAuth(),[rows,setRows]=useState<BreakRecord[]>([]),[types,setTypes]=useState<BreakType[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[date,setDate]=useState(""),[department,setDepartment]=useState("ALL"),[type,setType]=useState("ALL"),[status,setStatus]=useState("ALL"),[editing,setEditing]=useState<BreakRecord|null>(null),[reason,setReason]=useState(""),[startedAt,setStartedAt]=useState(""),[endedAt,setEndedAt]=useState(""),[editType,setEditType]=useState(""),[remarks,setRemarks]=useState(""),[showTypes,setShowTypes]=useState(false),[typeForm,setTypeForm]=useState({id:"",name:"",code:"",isActive:true,sortOrder:100});
 const canManage=hasPermission("breaks.manage"),canTypes=hasPermission("break_types.manage"),canExport=hasPermission("breaks.export");
 const load=useCallback(async()=>{setLoading(true);try{const[records,breakTypes]=await Promise.all([BreakService.getRecords(),BreakService.getTypes(true)]);setRows(records);setTypes(breakTypes)}catch(error){notifyError("Break records unavailable",error instanceof Error?error.message:"Unable to load break records")}finally{setLoading(false)}},[]);
 // Load the permission-scoped register when the workspace mounts.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load]);
 const departments=[...new Set(rows.map(row=>row.department))].sort();
 const filtered=useMemo(()=>rows.filter(row=>(!date||row.workDate===date)&&(department==="ALL"||row.department===department)&&(type==="ALL"||row.breakTypeId===type)&&(status==="ALL"||row.status===status)&&`${row.fullName} ${row.employeeCode} ${row.department}`.toLowerCase().includes(query.toLowerCase())),[rows,date,department,type,status,query]);
 const summary=useMemo(()=>{const completed=filtered.filter(row=>row.status==="COMPLETED"||row.status==="MANUALLY_ADJUSTED"),seconds=completed.reduce((total,row)=>total+(row.actualSeconds??0),0);return{active:filtered.filter(row=>row.status==="ACTIVE").length,completed:completed.length,seconds,average:completed.length?Math.round(seconds/completed.length):0}},[filtered]);
 const openEdit=(row:BreakRecord)=>{setEditing(row);setReason("");setStartedAt(localInput(row.startedAt));setEndedAt(localInput(row.endedAt));setEditType(row.breakTypeId);setRemarks(row.remarks??"")};
 const saveEdit=async(action:"ADJUST"|"CLOSE"|"CANCEL")=>{if(!editing)return;try{await BreakService.manage(editing.id,action,reason,{startedAt:isoFromNepal(startedAt),endedAt:isoFromNepal(endedAt),breakTypeId:editType,remarks});setEditing(null);await load();notifySuccess("Break record updated","The original and corrected values were written to the audit trail.")}catch(error){notifyError("Break record not updated",error instanceof Error?error.message:"Unable to save the correction")}};
 const saveType=async()=>{try{await BreakService.saveType({id:typeForm.id||undefined,name:typeForm.name.trim(),code:typeForm.code.trim().toUpperCase().replace(/[^A-Z0-9]+/g,"_"),isActive:typeForm.isActive,sortOrder:typeForm.sortOrder});setTypeForm({id:"",name:"",code:"",isActive:true,sortOrder:100});await load();notifySuccess("Break type saved","The option is available according to its active status.")}catch(error){notifyError("Break type not saved",error instanceof Error?error.message:"Unable to save break type")}};
 const exportCsv=()=>{const columns=["Date","Employee ID","Employee","Department","Break type","Start","End","Duration seconds","Status","Remarks"];const csv=[columns,...filtered.map(row=>[row.workDate,row.employeeCode,row.fullName,row.department,row.breakType,row.startedAt,row.endedAt??"",row.actualSeconds??"",row.status,row.remarks??""])].map(line=>line.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`employee-break-records-${date||"all"}.csv`;link.click();URL.revokeObjectURL(url)};
 return <div className="break-management"><BreakWidget/><section className="crm-panel"><div className="panel-header-bar"><div><h3>Employee Break Records</h3><p>Attendance-linked records using authoritative server timestamps and permission-scoped visibility.</p></div><div className="panel-header-actions">{canTypes&&<button type="button" className="btn-secondary" onClick={()=>setShowTypes(!showTypes)}><Coffee size={14}/>Break types</button>}{canExport&&<button type="button" className="btn-secondary" onClick={exportCsv} disabled={!filtered.length}><Download size={14}/>Export CSV</button>}</div></div>
 <div className="break-summary-grid"><article><span>Visible records</span><strong>{filtered.length}</strong></article><article><span>Active now</span><strong>{summary.active}</strong></article><article><span>Completed</span><strong>{summary.completed}</strong></article><article><span>Total break time</span><strong>{formatBreakDuration(summary.seconds)}</strong></article><article><span>Average duration</span><strong>{formatBreakDuration(summary.average)}</strong></article></div>
 <div className="break-filters"><label><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee or ID"/></label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="ALL">All departments</option>{departments.map(value=><option key={value}>{value}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="ALL">All break types</option>{types.map(value=><option value={value.id} key={value.id}>{value.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{["ACTIVE","COMPLETED","MANUALLY_ADJUSTED","CANCELLED"].map(value=><option key={value}>{value}</option>)}</select><span>{filtered.length} records</span></div>
 <div className="table-wrapper"><table className="crm-table"><thead><tr><th>Employee</th><th>Department</th><th>Break type</th><th>Start</th><th>End</th><th>Duration</th><th>Status</th><th>Remarks</th>{canManage&&<th/>}</tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><strong>{row.fullName}</strong><small>{row.employeeCode} · {row.workDate}</small></td><td>{row.department}</td><td>{row.breakType}</td><td>{new Date(row.startedAt).toLocaleString([],{timeZone:"Asia/Kathmandu"})}</td><td>{row.status==="CANCELLED"?"—":row.endedAt?new Date(row.endedAt).toLocaleTimeString([],{timeZone:"Asia/Kathmandu"}):"—"}</td><td>{row.status==="CANCELLED"?"Cancelled":row.actualSeconds==null?"Active":formatBreakDuration(row.actualSeconds)}</td><td><span className={`badge-status ${row.status==="ACTIVE"?"counselling":row.status==="CANCELLED"?"visa":"enrolled"}`}>{row.status.replaceAll("_"," ")}</span></td><td>{row.remarks||"—"}</td>{canManage&&<td><button type="button" className="btn-secondary" onClick={()=>openEdit(row)}><Pencil size={13}/>Correct</button></td>}</tr>)}{!loading&&!filtered.length&&<tr><td colSpan={canManage?9:8} className="employee-table-empty">No break records match these filters.</td></tr>}</tbody></table></div></section>
 {showTypes&&canTypes&&<section className="crm-panel break-types-panel"><div className="panel-header-bar"><div><h3>Break Types</h3><p>Rename, disable, or add employee break options.</p></div></div><div className="break-type-editor"><input placeholder="Name" value={typeForm.name} onChange={e=>setTypeForm({...typeForm,name:e.target.value,code:typeForm.id?typeForm.code:e.target.value.toUpperCase().replace(/[^A-Z0-9]+/g,"_")})}/><input placeholder="CODE" value={typeForm.code} onChange={e=>setTypeForm({...typeForm,code:e.target.value})}/><input type="number" value={typeForm.sortOrder} onChange={e=>setTypeForm({...typeForm,sortOrder:Number(e.target.value)})}/><label><input type="checkbox" checked={typeForm.isActive} onChange={e=>setTypeForm({...typeForm,isActive:e.target.checked})}/>Active</label><button type="button" className="btn-primary" onClick={()=>void saveType()}><Plus size={14}/>{typeForm.id?"Save":"Add type"}</button></div><div className="break-type-list">{types.map(item=><button type="button" key={item.id} onClick={()=>setTypeForm({id:item.id,name:item.name,code:item.code,isActive:item.isActive,sortOrder:item.sortOrder})}><strong>{item.name}</strong><small>{item.code}</small><span>{item.isActive?"Active":"Disabled"}</span></button>)}</div></section>}
 {editing&&<div className="modal-backdrop-clean" onClick={()=>setEditing(null)}><div className="modal-dialog-clean" onClick={e=>e.stopPropagation()}><div className="modal-header-clean"><div><span className="page-category-eyebrow">Audited HR correction</span><h3>Correct Break Record</h3><p>{editing.fullName} · {editing.employeeCode}</p></div><button className="drawer-close-btn" onClick={()=>setEditing(null)}><X size={17}/></button></div><div className="modal-body-clean"><div className="form-row-2"><label className="form-group">Start time<input type="datetime-local" value={startedAt} onChange={e=>setStartedAt(e.target.value)}/></label><label className="form-group">End time<input type="datetime-local" value={endedAt} onChange={e=>setEndedAt(e.target.value)}/></label></div><label className="form-group">Break type<select value={editType} onChange={e=>setEditType(e.target.value)}>{types.filter(item=>item.isActive||item.id===editing.breakTypeId).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="form-group">Remarks<textarea value={remarks} onChange={e=>setRemarks(e.target.value)}/></label><label className="form-group">Correction reason *<textarea required minLength={5} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required for the immutable audit trail"/></label></div><div className="modal-footer-clean"><button className="btn-secondary" disabled={reason.trim().length<5} onClick={()=>void saveEdit("CANCEL")}>Cancel record</button><button className="btn-primary" disabled={reason.trim().length<5} onClick={()=>void saveEdit(editing.status==="ACTIVE"?"CLOSE":"ADJUST")}>{editing.status==="ACTIVE"?"Close break":"Save correction"}</button></div></div></div>}
 </div>;
}
