import { useEffect,useMemo,useState } from "react";
import { Bell,Building2,CalendarClock,FileText,Network,Plus,ReceiptText,Save,Settings2,ShieldCheck,Target,Trash2,Users } from "lucide-react";
import { HrmsConfigurationService,type HrConfigRow } from "../../services/hrmsConfigurationService";
import { notifyError,notifySuccess } from "../../components/common/CrmNotifications";

type Tab="directory"|"numbering"|"attendance"|"compensation"|"tax"|"talent"|"documents"|"workflow";
const tabs:Array<{id:Tab;label:string;icon:typeof Users}>=[
  {id:"directory",label:"Departments & designations",icon:Building2},{id:"numbering",label:"Employee numbering",icon:Users},
  {id:"attendance",label:"Attendance & leave",icon:CalendarClock},{id:"compensation",label:"Salary & payroll",icon:ReceiptText},
  {id:"tax",label:"TDS configuration",icon:ShieldCheck},{id:"talent",label:"KPI & appraisal",icon:Target},
  {id:"documents",label:"Documents & contracts",icon:FileText},{id:"workflow",label:"Approvals & notifications",icon:Network},
];
const text=(value:unknown,fallback="—")=>String(value??fallback);

export function HrmsSettingsWorkspace(){
  const[tab,setTab]=useState<Tab>("directory"),[data,setData]=useState<Record<string,HrConfigRow[]>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  const[form,setForm]=useState<Record<string,string>>({});
  const load=async()=>{setLoading(true);try{setData(await HrmsConfigurationService.loadSettings())}catch(error){notifyError("HRMS settings unavailable",error instanceof Error?error.message:"Configuration could not be loaded")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const rows=useMemo(()=>{
    if(tab==="directory")return [...(data.hr_departments??[]),...(data.hr_designations??[])];
    if(tab==="attendance")return [...(data.hr_attendance_policies??[]),...(data.hr_leave_policies??[])];
    if(tab==="compensation")return [...(data.hr_salary_component_definitions??[]),...(data.hr_payroll_policies??[])];
    if(tab==="tax")return [...(data.hr_tax_rule_sets??[]),...(data.hr_tax_brackets??[])];
    if(tab==="talent")return [...(data.hr_kpi_templates??[]),...(data.hr_appraisal_cycles??[])];
    if(tab==="documents")return [...(data.hr_document_types??[]),...(data.hr_contracts??[])];
    if(tab==="workflow")return [...(data.hr_approval_routes??[]),...(data.hr_approval_route_steps??[]),...(data.hr_notification_rules??[])];
    return data.hr_employee_number_settings??[];
  },[data,tab]);
  const set=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
  const reset=()=>setForm({});
  const add=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);try{
    if(tab==="directory"){
      if(form.kind==="designation")await HrmsConfigurationService.insert("hr_designations",{code:form.code.trim().toUpperCase(),name:form.name.trim(),grade:form.grade||null,department_id:form.departmentId||null});
      else await HrmsConfigurationService.insert("hr_departments",{code:form.code.trim().toUpperCase(),name:form.name.trim()});
    } else if(tab==="attendance"){
      if(form.kind==="leave")await HrmsConfigurationService.insert("hr_leave_policies",{leave_type:form.name,monthly_credit:Number(form.monthlyCredit||0),is_paid:form.isPaid!=="false",allow_half_day:form.halfDay!=="false",monthly_carry_forward:form.carryForward!=="false",year_end_action:form.yearEndAction||"RESET",max_year_end_carry:Number(form.maxCarry||0),medical_document_after_days:Number(form.medicalAfter||0)||null});
      else await HrmsConfigurationService.insert("hr_attendance_policies",{name:form.name,effective_from:form.effectiveFrom,standard_daily_minutes:Number(form.dailyMinutes||480),standard_weekly_minutes:Number(form.weeklyMinutes||2880),grace_minutes:Number(form.grace||15),overtime_multiplier:Number(form.overtimeMultiplier||1.5),overtime_daily_cap_minutes:Number(form.overtimeDailyCap||240),overtime_weekly_cap_minutes:Number(form.overtimeWeeklyCap||1440),status:"DRAFT"});
    } else if(tab==="compensation"){
      if(form.kind==="policy")await HrmsConfigurationService.insert("hr_payroll_policies",{name:form.name,fiscal_year:form.fiscalYear,effective_from:form.effectiveFrom,daily_rate_method:form.dailyRate||"ACTUAL_BS_MONTH_DAYS",rounding_method:"NET_PAY_ONLY",minimum_monthly_pay:Number(form.minimumPay||0)||null,minimum_basic_pay:Number(form.minimumBasic||0)||null,minimum_basic_ratio:Number(form.minimumRatio||0)||null,status:"DRAFT"});
      else await HrmsConfigurationService.insert("hr_salary_component_definitions",{code:form.code.trim().toUpperCase(),name:form.name,component_type:form.componentType||"EARNING",calculation_method:form.calculationMethod||"FIXED",default_value:Number(form.defaultValue||0),taxable:form.taxable!=="false",statutory:form.statutory==="true",effective_from:form.effectiveFrom});
    } else if(tab==="tax"){
      if(form.kind==="bracket")await HrmsConfigurationService.insert("hr_tax_brackets",{rule_set_id:form.ruleSetId,sequence:Number(form.sequence),lower_bound:Number(form.lowerBound||0),upper_bound:form.upperBound?Number(form.upperBound):null,rate:Number(form.rate||0)/100});
      else await HrmsConfigurationService.insert("hr_tax_rule_sets",{name:form.name,fiscal_year:form.fiscalYear,effective_from:form.effectiveFrom,employee_ssf_rate:Number(form.employeeSsf||0)/100,employer_ssf_rate:Number(form.employerSsf||0)/100,retirement_cap_amount:Number(form.retirementCap||0)||null,retirement_cap_income_ratio:Number(form.retirementRatio||0)/100||null,status:"DRAFT",source_reference:form.source});
    } else if(tab==="talent"){
      if(form.kind==="cycle")await HrmsConfigurationService.insert("hr_appraisal_cycles",{name:form.name,period_start:form.periodStart,period_end:form.periodEnd,self_review_due:form.selfDue||null,manager_review_due:form.managerDue||null,status:"DRAFT"});
      else await HrmsConfigurationService.insert("hr_kpi_templates",{code:form.code.trim().toUpperCase(),name:form.name,description:form.description||null,unit:form.unit||"COUNT",default_target:Number(form.target||0)||null,weight:Number(form.weight||100)/100});
    } else if(tab==="documents"){
      if(form.kind==="contract")await HrmsConfigurationService.insert("hr_contracts",{employee_id:form.employeeId,contract_number:form.code.trim().toUpperCase(),contract_type:form.contractType||"EMPLOYMENT",start_date:form.startDate,end_date:form.endDate||null,status:"DRAFT",notes:form.notes||null});
      else await HrmsConfigurationService.insert("hr_document_types",{code:form.code.trim().toUpperCase(),name:form.name,category:form.category||"EMPLOYEE",mandatory:form.mandatory==="true",has_expiry:form.hasExpiry==="true"});
    } else if(tab==="workflow"){
      if(form.kind==="notification")await HrmsConfigurationService.insert("hr_notification_rules",{event_type:form.code.trim().toUpperCase(),title_template:form.name,body_template:form.body,channels:["IN_APP"],recipient_rule:form.recipient||"SUBJECT"});
      else if(form.kind==="step")await HrmsConfigurationService.insert("hr_approval_route_steps",{route_id:form.routeId,sequence:Number(form.sequence),approver_type:form.approverType||"MANAGER",approver_value:form.approverValue||null});
      else await HrmsConfigurationService.insert("hr_approval_routes",{code:form.code.trim().toUpperCase(),name:form.name,workflow_type:form.workflowType||"LEAVE"});
    }
    reset();await load();notifySuccess("Configuration saved","The new HRMS rule is available without changing historical records.");
  }catch(error){notifyError("Configuration not saved",error instanceof Error?error.message:"Review the entered values")}finally{setSaving(false)}};
  const saveNumbering=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);try{await HrmsConfigurationService.updateNumbering({prefix:form.prefix||"AECS-EMP-",padding:Number(form.padding||4),next_number:Number(form.nextNumber||1),include_fiscal_year:form.includeFiscal==="true",separator:form.separator||"-"});await load();notifySuccess("Employee numbering updated","The next employee record will use the new sequence.")}catch(error){notifyError("Numbering not saved",error instanceof Error?error.message:"Check the sequence values")}finally{setSaving(false)}};
  const activate=async(row:HrConfigRow)=>{const table=(data.hr_attendance_policies??[]).some(item=>item.id===row.id)?"hr_attendance_policies":(data.hr_payroll_policies??[]).some(item=>item.id===row.id)?"hr_payroll_policies":"hr_tax_rule_sets";try{await HrmsConfigurationService.setRuleStatus(table,row.id,"ACTIVE");await load();notifySuccess("Rule activated","Previous active rules were retired and history was preserved.")}catch(error){notifyError("Activation failed",error instanceof Error?error.message:"Rule could not be activated")}};
  return <div className="page-container">
    <section className="page-heading"><div><p className="eyebrow">Human resources configuration</p><h2>HRMS Settings Centre</h2><p>Effective-dated policies and master data that control employee, attendance, payroll and compliance workflows.</p></div><span className="status-pill"><ShieldCheck size={14}/> Permission controlled</span></section>
    <div style={{display:"grid",gridTemplateColumns:"260px minmax(0,1fr)",gap:18,alignItems:"start"}}>
      <aside className="panel" style={{padding:10,position:"sticky",top:84}}>{tabs.map(item=>{const Icon=item.icon;return <button key={item.id} type="button" className={tab===item.id?"sidebar-link active":"sidebar-link"} style={{width:"100%",border:0,marginBottom:4}} onClick={()=>{setTab(item.id);reset()}}><div className="sidebar-link-content"><Icon size={16}/><span>{item.label}</span></div></button>})}</aside>
      <main style={{display:"grid",gap:16}}>
        <section className="panel" style={{padding:20}}><header style={{display:"flex",justifyContent:"space-between",gap:12,marginBottom:16}}><div><p className="eyebrow">{tabs.find(item=>item.id===tab)?.label}</p><h3 style={{margin:"4px 0"}}>Configuration register</h3><small>{loading?"Loading…":`${rows.length} configured records`}</small></div><Settings2 size={22}/></header>
          {tab === "numbering"
            ? <NumberingForm row={rows[0]} form={form} set={set} submit={saveNumbering} saving={saving}/>
            : <ConfigForm tab={tab} form={form} set={set} submit={add} saving={saving} departments={data.hr_departments??[]} employees={data.hr_employees??[]} taxRules={data.hr_tax_rule_sets??[]} routes={data.hr_approval_routes??[]}/>}
        </section>
        <section className="panel"><div className="table-wrapper"><table className="crm-table"><thead><tr><th>Configuration</th><th>Type / period</th><th>Key values</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={`${tab}-${row.id}`}><td><strong>{text(row.name,row.leave_type?text(row.leave_type):text(row.prefix))}</strong><small>{text(row.code,row.fiscal_year?`FY ${text(row.fiscal_year)}`:text(row.event_type,"Versioned HR rule"))}</small></td><td>{text(row.workflow_type,row.component_type?text(row.component_type):row.effective_from?`From ${text(row.effective_from)}`:text(row.category,"Configuration"))}</td><td><small>{summary(row)}</small></td><td><span className={`badge-status ${row.status==="ACTIVE"||row.is_active===true?"enrolled":"counselling"}`}>{text(row.status,row.is_active===false?"INACTIVE":"ACTIVE")}</span></td><td><div className="table-actions">{["DRAFT","RETIRED"].includes(text(row.status,""))&&<button className="btn-secondary" type="button" onClick={()=>void activate(row)}>Activate</button>}<button className="btn-secondary" type="button" aria-label="Delete configuration" onClick={async()=>{if(!confirm("Delete this configuration record? Historical operational records will remain."))return;const table=findTable(data,row.id);if(table){await HrmsConfigurationService.remove(table,row.id);await load()}}}><Trash2 size={14}/></button></div></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={5} style={{padding:32,textAlign:"center"}}>No configuration records yet. Use the form above to add the first one.</td></tr>}</tbody></table></div></section>
      </main>
    </div>
  </div>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="form-group"><span>{label}</span>{children}</label>}
function Input({value,onChange,...props}:React.InputHTMLAttributes<HTMLInputElement>){return <input {...props} value={value??""} onChange={onChange}/>}
function ConfigForm({tab,form,set,submit,saving,departments,employees,taxRules,routes}:{tab:Tab;form:Record<string,string>;set:(k:string,v:string)=>void;submit:(e:React.FormEvent)=>void;saving:boolean;departments:HrConfigRow[];employees:HrConfigRow[];taxRules:HrConfigRow[];routes:HrConfigRow[]}){
  const input=(key:string)=>(event:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>set(key,event.target.value);
  return <form onSubmit={submit}><div className="form-row-2">
    {tab==="directory"&&<><Field label="Record type"><select value={form.kind||"department"} onChange={input("kind")}><option value="department">Department</option><option value="designation">Designation</option></select></Field><Field label="Code"><Input required value={form.code} onChange={input("code")} placeholder="HRADM"/></Field><Field label="Name"><Input required value={form.name} onChange={input("name")} placeholder="HR & Administration"/></Field>{form.kind==="designation"&&<><Field label="Department"><select value={form.departmentId||""} onChange={input("departmentId")}><option value="">Organization-wide</option>{departments.map(row=><option key={row.id} value={row.id}>{text(row.name)}</option>)}</select></Field><Field label="Grade"><Input value={form.grade} onChange={input("grade")} placeholder="G5"/></Field></>}</>}
    {tab==="attendance"&&<><Field label="Configuration type"><select value={form.kind||"attendance"} onChange={input("kind")}><option value="attendance">Attendance policy</option><option value="leave">Leave policy</option></select></Field><Field label={form.kind==="leave"?"Leave type":"Policy name"}><Input required value={form.name} onChange={input("name")}/></Field>{form.kind==="leave"?<><Field label="Monthly credit (days)"><Input type="number" step="0.5" value={form.monthlyCredit||"0.5"} onChange={input("monthlyCredit")}/></Field><Field label="Paid leave"><select value={form.isPaid||"true"} onChange={input("isPaid")}><option value="true">Yes</option><option value="false">No</option></select></Field><Field label="Year-end action"><select value={form.yearEndAction||"RESET"} onChange={input("yearEndAction")}><option>RESET</option><option>CARRY_FORWARD</option></select></Field><Field label="Maximum carry"><Input type="number" step="0.5" value={form.maxCarry||"0"} onChange={input("maxCarry")}/></Field></>:<><Field label="Effective from"><Input required type="date" value={form.effectiveFrom} onChange={input("effectiveFrom")}/></Field><Field label="Daily minutes"><Input type="number" value={form.dailyMinutes||"480"} onChange={input("dailyMinutes")}/></Field><Field label="Weekly minutes"><Input type="number" value={form.weeklyMinutes||"2880"} onChange={input("weeklyMinutes")}/></Field><Field label="Grace minutes"><Input type="number" value={form.grace||"15"} onChange={input("grace")}/></Field><Field label="Overtime multiplier"><Input type="number" step="0.1" value={form.overtimeMultiplier||"1.5"} onChange={input("overtimeMultiplier")}/></Field></>}</>}
    {tab==="compensation"&&<><Field label="Configuration type"><select value={form.kind||"component"} onChange={input("kind")}><option value="component">Salary component</option><option value="policy">Payroll policy</option></select></Field><Field label="Name"><Input required value={form.name} onChange={input("name")}/></Field>{form.kind==="policy"?<><Field label="Fiscal year"><Input required value={form.fiscalYear} onChange={input("fiscalYear")} placeholder="2083/84"/></Field><Field label="Effective from"><Input required type="date" value={form.effectiveFrom} onChange={input("effectiveFrom")}/></Field><Field label="Minimum monthly pay"><Input type="number" value={form.minimumPay} onChange={input("minimumPay")}/></Field><Field label="Minimum basic pay"><Input type="number" value={form.minimumBasic} onChange={input("minimumBasic")}/></Field></>:<><Field label="Code"><Input required value={form.code} onChange={input("code")}/></Field><Field label="Component type"><select value={form.componentType||"EARNING"} onChange={input("componentType")}><option>EARNING</option><option>DEDUCTION</option><option>EMPLOYER_CONTRIBUTION</option></select></Field><Field label="Calculation"><select value={form.calculationMethod||"FIXED"} onChange={input("calculationMethod")}><option>FIXED</option><option>PERCENT_BASIC</option><option>PERCENT_GROSS</option><option>FORMULA</option></select></Field><Field label="Default value"><Input type="number" step="0.01" value={form.defaultValue} onChange={input("defaultValue")}/></Field><Field label="Effective from"><Input required type="date" value={form.effectiveFrom} onChange={input("effectiveFrom")}/></Field></>}</>}
    {tab==="tax"&&<><Field label="Configuration type"><select value={form.kind||"rules"} onChange={input("kind")}><option value="rules">Tax rule set</option><option value="bracket">Tax bracket</option></select></Field>{form.kind==="bracket"?<><Field label="Rule set"><select required value={form.ruleSetId||""} onChange={input("ruleSetId")}><option value="">Select rule set</option>{taxRules.map(row=><option key={row.id} value={row.id}>{text(row.name)}</option>)}</select></Field><Field label="Sequence"><Input required type="number" value={form.sequence} onChange={input("sequence")}/></Field><Field label="Lower bound"><Input required type="number" value={form.lowerBound||"0"} onChange={input("lowerBound")}/></Field><Field label="Upper bound"><Input type="number" value={form.upperBound} onChange={input("upperBound")} placeholder="No limit"/></Field><Field label="Rate %"><Input required type="number" step="0.01" value={form.rate} onChange={input("rate")}/></Field></>:<><Field label="Rule-set name"><Input required value={form.name} onChange={input("name")}/></Field><Field label="Fiscal year"><Input required value={form.fiscalYear} onChange={input("fiscalYear")}/></Field><Field label="Effective from"><Input required type="date" value={form.effectiveFrom} onChange={input("effectiveFrom")}/></Field><Field label="Employee SSF %"><Input type="number" step="0.01" value={form.employeeSsf||"11"} onChange={input("employeeSsf")}/></Field><Field label="Employer SSF %"><Input type="number" step="0.01" value={form.employerSsf||"20"} onChange={input("employerSsf")}/></Field><Field label="Retirement cap NPR"><Input type="number" value={form.retirementCap||"500000"} onChange={input("retirementCap")}/></Field><Field label="Source reference"><Input value={form.source} onChange={input("source")}/></Field></>}</>}
    {tab==="talent"&&<><Field label="Configuration type"><select value={form.kind||"kpi"} onChange={input("kind")}><option value="kpi">KPI template</option><option value="cycle">Appraisal cycle</option></select></Field><Field label="Name"><Input required value={form.name} onChange={input("name")}/></Field>{form.kind==="cycle"?<><Field label="Period start"><Input required type="date" value={form.periodStart} onChange={input("periodStart")}/></Field><Field label="Period end"><Input required type="date" value={form.periodEnd} onChange={input("periodEnd")}/></Field><Field label="Self-review due"><Input type="date" value={form.selfDue} onChange={input("selfDue")}/></Field><Field label="Manager-review due"><Input type="date" value={form.managerDue} onChange={input("managerDue")}/></Field></>:<><Field label="Code"><Input required value={form.code} onChange={input("code")}/></Field><Field label="Unit"><select value={form.unit||"COUNT"} onChange={input("unit")}><option>COUNT</option><option>PERCENT</option><option>NPR</option><option>SCORE</option></select></Field><Field label="Default target"><Input type="number" value={form.target} onChange={input("target")}/></Field><Field label="Weight %"><Input type="number" value={form.weight||"100"} onChange={input("weight")}/></Field></>}</>}
    {tab==="documents"&&<><Field label="Configuration type"><select value={form.kind||"document"} onChange={input("kind")}><option value="document">Document type</option><option value="contract">Employee contract</option></select></Field><Field label={form.kind==="contract"?"Contract number":"Document code"}><Input required value={form.code} onChange={input("code")}/></Field>{form.kind==="contract"?<><Field label="Employee"><select required value={form.employeeId||""} onChange={input("employeeId")}><option value="">Select employee</option>{employees.map(row=><option key={row.id} value={row.id}>{text(row.employee_code)} · {text(row.full_name)}</option>)}</select></Field><Field label="Contract type"><Input required value={form.contractType||"EMPLOYMENT"} onChange={input("contractType")}/></Field><Field label="Start date"><Input required type="date" value={form.startDate} onChange={input("startDate")}/></Field><Field label="End date"><Input type="date" value={form.endDate} onChange={input("endDate")}/></Field><Field label="Notes"><Input value={form.notes} onChange={input("notes")}/></Field></>:<><Field label="Document type"><Input required value={form.name} onChange={input("name")}/></Field><Field label="Category"><select value={form.category||"EMPLOYEE"} onChange={input("category")}><option>EMPLOYEE</option><option>CONTRACT</option><option>STATUTORY</option><option>QUALIFICATION</option></select></Field><Field label="Mandatory"><select value={form.mandatory||"false"} onChange={input("mandatory")}><option value="false">No</option><option value="true">Yes</option></select></Field><Field label="Has expiry"><select value={form.hasExpiry||"false"} onChange={input("hasExpiry")}><option value="false">No</option><option value="true">Yes</option></select></Field></>}</>}
    {tab==="workflow"&&<><Field label="Configuration type"><select value={form.kind||"route"} onChange={input("kind")}><option value="route">Approval route</option><option value="step">Approval step</option><option value="notification">Notification rule</option></select></Field>{form.kind==="step"?<><Field label="Approval route"><select required value={form.routeId||""} onChange={input("routeId")}><option value="">Select route</option>{routes.map(row=><option key={row.id} value={row.id}>{text(row.name)}</option>)}</select></Field><Field label="Sequence"><Input required type="number" value={form.sequence} onChange={input("sequence")}/></Field><Field label="Approver type"><select value={form.approverType||"MANAGER"} onChange={input("approverType")}><option>MANAGER</option><option>ROLE</option><option>EMPLOYEE</option></select></Field><Field label="Role or employee ID"><Input value={form.approverValue} onChange={input("approverValue")}/></Field></>:<><Field label="Code / event"><Input required value={form.code} onChange={input("code")}/></Field><Field label="Name / title"><Input required value={form.name} onChange={input("name")}/></Field>{form.kind==="notification"?<><Field label="Message template"><textarea required value={form.body||""} onChange={input("body")}/></Field><Field label="Recipient"><select value={form.recipient||"SUBJECT"} onChange={input("recipient")}><option>SUBJECT</option><option>MANAGER</option><option>HR</option><option>PAYROLL</option></select></Field></>:<Field label="Workflow"><select value={form.workflowType||"LEAVE"} onChange={input("workflowType")}><option>LEAVE</option><option>ATTENDANCE_CORRECTION</option><option>OVERTIME</option><option>SALARY_CHANGE</option><option>PAYROLL</option><option>CONTRACT</option><option>APPRAISAL</option></select></Field>}</>}</>}
  </div><button className="btn-primary" disabled={saving} type="submit"><Plus size={15}/>{saving?"Saving…":"Add configuration"}</button></form>
}
function NumberingForm({row,form,set,submit,saving}:{row?:HrConfigRow;form:Record<string,string>;set:(k:string,v:string)=>void;submit:(e:React.FormEvent)=>void;saving:boolean}){const value=(key:string,column:string,fallback:string)=>form[key]??text(row?.[column],fallback);return <form onSubmit={submit}><div className="form-row-2"><Field label="Prefix"><Input required value={value("prefix","prefix","AECS-EMP-")} onChange={e=>set("prefix",e.target.value)}/></Field><Field label="Padding"><Input required type="number" min="2" max="10" value={value("padding","padding","4")} onChange={e=>set("padding",e.target.value)}/></Field><Field label="Next number"><Input required type="number" min="1" value={value("nextNumber","next_number","1")} onChange={e=>set("nextNumber",e.target.value)}/></Field><Field label="Include fiscal year"><select value={value("includeFiscal","include_fiscal_year","false")} onChange={e=>set("includeFiscal",e.target.value)}><option value="false">No</option><option value="true">Yes</option></select></Field><Field label="Separator"><Input required value={value("separator","separator","-")} onChange={e=>set("separator",e.target.value)}/></Field></div><button className="btn-primary" disabled={saving} type="submit"><Save size={15}/>{saving?"Saving…":"Save numbering"}</button></form>}
function summary(row:HrConfigRow){const values=[row.department,row.grade,row.fiscal_year,row.standard_daily_minutes&&`${row.standard_daily_minutes} min/day`,row.grace_minutes&&`${row.grace_minutes} min grace`,row.default_value,row.employee_ssf_rate&&`${Number(row.employee_ssf_rate)*100}% employee SSF`,row.period_start&&`${row.period_start} to ${row.period_end}`,row.mandatory===true&&"Mandatory",row.workflow_type,row.channels&&String(row.channels)].filter(Boolean);return values.slice(0,3).join(" · ")||"Configured master record"}
function findTable(data:Record<string,HrConfigRow[]>,id:string){return Object.entries(data).find(([,rows])=>rows.some(row=>row.id===id))?.[0]}

export default HrmsSettingsWorkspace;
