import { supabase } from "../lib/supabase";
import { generateUuid } from "../lib/generateUuid";
export interface ClassStudent{id:string;studentCode:string;linkedStudentId?:string;photoPath?:string;fullName:string;phone:string;altPhone?:string;email?:string;gender?:"Male"|"Female"|"Other";educationLevel?:string;guardianName?:string;guardianPhone?:string;address?:string;recordStatus:"Active"|"Completed"|"On Hold"|"Dropped";notes?:string;enrolledClass:string;teacher:string;startDate:string;expectedCompletion:string;batchName:string;schedule:string;mode:"Classroom"|"Online"|"Hybrid";classStatus:"Active"|"Completed"|"Transferred"|"On Hold";enrolmentNotes?:string;feePaid:string;createdAt:string}
export interface BatchRecord{id:string;batchCode:string;courseName:string;courseType:string;timing:string;instructor:string;facultyId?:string;enrolledStudents:number;maxCapacity:number;room:string;startDate:string;status:"ACTIVE"|"UPCOMING"|"COMPLETED"}
export interface ClassAttendanceRecord { classStudentId:string; status:"PRESENT"|"ABSENT"|"LATE"|"EXCUSED"; markedAt:string }
export interface AttendanceHistoryRecord { id:string; classStudentId:string; sessionDate:string; batchCode:string; courseName:string; status:ClassAttendanceRecord["status"]; markedAt:string }
export interface ClassFaculty { id:string; fullName:string; email:string; phone:string; specialization:string; qualification:string; employmentType:"Full-time"|"Part-time"|"Visiting"; status:"ACTIVE"|"INACTIVE"; notes:string; createdAt:string }
type Row={id:string;student_code:string;linked_student_id:string|null;photo_path:string|null;full_name:string;phone:string;alt_phone:string|null;email:string|null;gender:ClassStudent["gender"];education_level:string|null;guardian_name:string|null;guardian_phone:string|null;address:string|null;record_status:ClassStudent["recordStatus"];notes:string|null;created_at:string;batch_enrollments?:Array<{mode:ClassStudent["mode"];expected_completion:string|null;status:ClassStudent["classStatus"];notes:string|null;test_prep_batches?:{batch_code:string;title:string;timing:string;instructor_name:string;start_date:string}|null}>};
type AttendanceHistoryRow={id:string;status:ClassAttendanceRecord["status"];marked_at:string;batch_enrollments:{class_student_id:string}|Array<{class_student_id:string}>;attendance_sessions:{session_date:string;test_prep_batches:{batch_code:string;title:string}|Array<{batch_code:string;title:string}>}|Array<{session_date:string;test_prep_batches:{batch_code:string;title:string}|Array<{batch_code:string;title:string}>}>};
type FacultyRow={id:string;full_name:string;email:string|null;phone:string|null;specialization:string|null;qualification:string|null;employment_type:ClassFaculty["employmentType"];status:ClassFaculty["status"];notes:string|null;created_at:string};
const courseType:Record<string,string>={"IELTS Preparation":"IELTS_PREP","PTE Academic":"PTE_ACADEMIC","Duolingo (DET)":"DUOLINGO_DET","German Language (A1/A2)":"GERMAN_A1","Japanese (NAT/JLPT)":"JAPANESE_N5","TOEFL iBT":"SAT_PREP","Korean (TOPIK)":"SAT_PREP"};
const serviceError=(error:{message?:string;details?:string;hint?:string}|null,fallback:string)=>new Error(error?.message||error?.details||error?.hint||fallback);
export const ClassStudentService={
 async getStudents():Promise<ClassStudent[]>{const{data,error}=await supabase.from("class_students").select("*,batch_enrollments(mode,expected_completion,status,notes,test_prep_batches(batch_code,title,timing,instructor_name,start_date))").order("created_at",{ascending:false});if(error)throw serviceError(error,"Unable to load class students");return((data??[])as unknown as Row[]).map(r=>{const e=r.batch_enrollments?.[0],b=e?.test_prep_batches;return{id:r.id,studentCode:r.student_code,linkedStudentId:r.linked_student_id??undefined,photoPath:r.photo_path??undefined,fullName:r.full_name,phone:r.phone,altPhone:r.alt_phone??undefined,email:r.email??undefined,gender:r.gender,educationLevel:r.education_level??undefined,guardianName:r.guardian_name??undefined,guardianPhone:r.guardian_phone??undefined,address:r.address??undefined,recordStatus:r.record_status,notes:r.notes??undefined,enrolledClass:(b?.title??"IELTS Preparation")as ClassStudent["enrolledClass"],teacher:b?.instructor_name??"Unassigned",startDate:b?.start_date??"",expectedCompletion:e?.expected_completion??"",batchName:b?.batch_code??"",schedule:b?.timing??"",mode:e?.mode??"Classroom",classStatus:e?.status??"Active",enrolmentNotes:e?.notes??undefined,feePaid:"Recorded in Finance",createdAt:r.created_at.slice(0,10)}})},
 async getBatches():Promise<BatchRecord[]>{const{data,error}=await supabase.from("test_prep_batches").select("*,batch_enrollments(count)").order("start_date",{ascending:false});if(error)throw error;return(data??[]).map(b=>({id:b.id,batchCode:b.batch_code,courseName:b.title,courseType:b.course_type,timing:b.timing,instructor:b.instructor_name,facultyId:b.faculty_id??undefined,enrolledStudents:Number(b.batch_enrollments?.[0]?.count??0),maxCapacity:b.max_capacity,room:b.room,startDate:b.start_date,status:b.status as BatchRecord["status"]}))},
 async getAttendance(date:string):Promise<ClassAttendanceRecord[]>{const{data,error}=await supabase.from("attendance_records").select("status,marked_at,batch_enrollments!inner(class_student_id),attendance_sessions!inner(session_date)").eq("attendance_sessions.session_date",date);if(error)throw error;return(data??[]).flatMap(row=>{const enrolment=Array.isArray(row.batch_enrollments)?row.batch_enrollments[0]:row.batch_enrollments;return enrolment?.class_student_id?[{classStudentId:enrolment.class_student_id,status:row.status as ClassAttendanceRecord["status"],markedAt:row.marked_at}]:[]})},
 async createStudent(student:Omit<ClassStudent,"id"|"studentCode"|"createdAt">){const{data,error}=await supabase.rpc("create_class_student",{payload:{linked_student_id:student.linkedStudentId??"",full_name:student.fullName,phone:student.phone,alt_phone:student.altPhone??"",email:student.email??"",gender:student.gender,education_level:student.educationLevel??"",guardian_name:student.guardianName??"",guardian_phone:student.guardianPhone??"",address:student.address??"",record_status:student.recordStatus,notes:student.notes??"",batch_code:student.batchName,mode:student.mode,expected_completion:student.expectedCompletion,class_status:student.classStatus,enrolment_notes:student.enrolmentNotes??""}});if(error)throw serviceError(error,"Unable to enrol class student");return data},
 async createBatch(batch:{batchCode:string;courseName:string;timing:string;instructor:string;facultyId?:string;maxCapacity:number;room:string;startDate:string;status:string}){const{error}=await supabase.rpc("create_test_batch",{payload:{batch_code:batch.batchCode,course_type:courseType[batch.courseName]??"SAT_PREP",title:batch.courseName,timing:batch.timing,instructor:batch.instructor,faculty_id:batch.facultyId??null,max_capacity:batch.maxCapacity,room:batch.room||"To be assigned",start_date:batch.startDate,status:batch.status}});if(error)throw serviceError(error,"Unable to create course batch")},
 async markAttendance(classStudentId:string,status:"PRESENT"|"ABSENT"|"LATE"|"EXCUSED",date=new Date().toISOString().slice(0,10)){const{error}=await supabase.rpc("mark_class_attendance",{class_student_uuid:classStudentId,attendance_date:date,attendance_status:status});if(error)throw error},
 async getAttendanceHistory():Promise<AttendanceHistoryRecord[]>{const{data,error}=await supabase.from("attendance_records").select("id,status,marked_at,batch_enrollments!inner(class_student_id),attendance_sessions!inner(session_date,test_prep_batches!inner(batch_code,title))").order("marked_at",{ascending:false});if(error)throw serviceError(error,"Unable to load attendance history");return((data??[]) as unknown as AttendanceHistoryRow[]).flatMap(row=>{const enrolment=Array.isArray(row.batch_enrollments)?row.batch_enrollments[0]:row.batch_enrollments;const session=Array.isArray(row.attendance_sessions)?row.attendance_sessions[0]:row.attendance_sessions;const batch=Array.isArray(session?.test_prep_batches)?session.test_prep_batches[0]:session?.test_prep_batches;return enrolment?.class_student_id&&session?.session_date?[{id:row.id,classStudentId:enrolment.class_student_id,sessionDate:session.session_date,batchCode:batch?.batch_code??"",courseName:batch?.title??"",status:row.status,markedAt:row.marked_at}]:[]})},
 async getFaculty():Promise<ClassFaculty[]>{const{data,error}=await supabase.from("class_faculty").select("*").neq("status","REMOVED").order("full_name");if(error)throw serviceError(error,"Unable to load faculty profiles");return((data??[]) as unknown as FacultyRow[]).map(r=>({id:r.id,fullName:r.full_name,email:r.email??"",phone:r.phone??"",specialization:r.specialization??"",qualification:r.qualification??"",employmentType:r.employment_type,status:r.status,notes:r.notes??"",createdAt:r.created_at}))},
 async saveFaculty(faculty:Omit<ClassFaculty,"id"|"createdAt">&{id?:string}){const{data,error}=await supabase.rpc("save_class_faculty",{faculty_uuid:faculty.id??null,payload:{full_name:faculty.fullName,email:faculty.email,phone:faculty.phone,specialization:faculty.specialization,qualification:faculty.qualification,employment_type:faculty.employmentType,status:faculty.status,notes:faculty.notes}});if(error)throw serviceError(error,"Unable to save faculty profile");return data as string},
 async removeFaculty(id:string){const{error}=await supabase.rpc("remove_class_faculty",{faculty_uuid:id});if(error)throw serviceError(error,"Unable to remove faculty profile")},
 async updateStudent(id:string,patch:Partial<ClassStudent>){const values:Record<string,unknown>={};const fields:Record<string,keyof ClassStudent>={full_name:"fullName",phone:"phone",alt_phone:"altPhone",email:"email",gender:"gender",education_level:"educationLevel",guardian_name:"guardianName",guardian_phone:"guardianPhone",address:"address",record_status:"recordStatus",notes:"notes"};for(const[db,key]of Object.entries(fields))if(patch[key]!==undefined)values[db]=patch[key]||null;const{data,error}=await supabase.from("class_students").update(values).eq("id",id).select("id");if(error)throw serviceError(error,"Unable to update class student");if(!data?.length)throw new Error("The class student was not updated");return true},
 async photoUrl(path:string){const{data,error}=await supabase.storage.from("student-documents").createSignedUrl(path,3600);if(error)throw serviceError(error,"Unable to open class student photo");return data.signedUrl},
 async uploadPhoto(student:ClassStudent,file:File){const user=(await supabase.auth.getUser()).data.user;if(!user)throw new Error("Sign in before uploading a photo");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${user.id}/class-students/${student.id}/${generateUuid()}-${safe}`;const{error:uploadError}=await supabase.storage.from("student-documents").upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw serviceError(uploadError,"Unable to upload photo");const{data,error}=await supabase.from("class_students").update({photo_path:path}).eq("id",student.id).select("id");if(error||!data?.length){await supabase.storage.from("student-documents").remove([path]);throw serviceError(error,"Unable to save photo")}if(student.photoPath)void supabase.storage.from("student-documents").remove([student.photoPath]);return path},
 async deleteStudent(id:string){const{error}=await supabase.from("class_students").delete().eq("id",id);if(error)throw error;return true},
};
