import { supabase } from "../lib/supabase";
export type DocumentStatus="VERIFIED"|"UNDER_REVIEW"|"ACTION_REQUIRED"|"REJECTED"|"EXPIRED";
export interface DocumentRecord{id:string;studentCode:string;studentName:string;fileName:string;category:string;fileSize:string;uploadedAt:string;status:DocumentStatus;verifiedBy?:string;notes?:string;storagePath:string;version:number;expiresOn?:string;mimeType:string;activities:Array<{action:string;createdAt:string;performedBy:string}>}
type Row={id:string;document_name:string;document_type:string;storage_path:string;file_size:number;mime_type:string;status:"UPLOADED"|"UNDER_REVIEW"|"APPROVED"|"ACTION_REQUIRED"|"REJECTED"|"EXPIRED";version:number;expires_on:string|null;notes:string|null;created_at:string;students?:{student_code:string;full_name:string}|null;staff_profiles?:{full_name:string}|null;document_activity?:Array<{action:string;created_at:string;staff_profiles?:{full_name:string}|null}>};
const uiStatus=(status:Row["status"]):DocumentStatus=>status==="APPROVED"?"VERIFIED":status==="UPLOADED"?"UNDER_REVIEW":status;
const dbType:Record<string,string>={"Passport & Identity":"Passport","Academic Transcripts":"Academic Documents","English Test Results":"English Test Result","Financial Documents":"Financial Documents","Visa & Embassy Files":"Visa Documents","Recommendation Letters":"Application Documents","Application Documents":"Application Documents","Profile Photo":"Other"};
const size=(bytes:number)=>bytes<1024*1024?`${Math.ceil(bytes/1024)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;
export const DocumentService={
 async list():Promise<DocumentRecord[]>{const{data,error}=await supabase.from("documents").select("*,students(student_code,full_name),staff_profiles!documents_verified_by_fkey(full_name),document_activity(action,created_at,staff_profiles!document_activity_performed_by_fkey(full_name))").order("created_at",{ascending:false});if(error)throw error;return((data??[])as unknown as Row[]).map(r=>({id:r.id,studentCode:r.students?.student_code??"—",studentName:r.students?.full_name??"Unknown",fileName:r.document_name,category:Object.entries(dbType).find(([,v])=>v===r.document_type)?.[0]??r.document_type,fileSize:size(r.file_size),uploadedAt:new Date(r.created_at).toLocaleString(),status:uiStatus(r.status),verifiedBy:r.staff_profiles?.full_name,notes:r.notes??undefined,storagePath:r.storage_path,version:r.version,expiresOn:r.expires_on??undefined,mimeType:r.mime_type,activities:(r.document_activity??[]).map(a=>({action:a.action,createdAt:a.created_at,performedBy:a.staff_profiles?.full_name??"Staff"})).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}))},
 async upload(input:{studentCode:string;category:string;title:string;file:File;expiresOn:string;notes:string}){const safe=input.file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${(await supabase.auth.getUser()).data.user?.id}/${crypto.randomUUID()}-${safe}`;const{error:uploadError}=await supabase.storage.from("student-documents").upload(path,input.file,{contentType:input.file.type,upsert:false});if(uploadError)throw uploadError;const{error}=await supabase.rpc("register_document",{payload:{student_code:input.studentCode,document_name:input.title,document_type:dbType[input.category]??"Other",storage_path:path,file_size:input.file.size,mime_type:input.file.type,expires_on:input.expiresOn,notes:input.notes}});if(error){await supabase.storage.from("student-documents").remove([path]);throw error}},
 async review(id:string,status:DocumentStatus,note=""){const mapped=status==="VERIFIED"?"APPROVED":status;const{error}=await supabase.rpc("review_document",{document_uuid:id,next_status:mapped,review_note:note});if(error)throw error},
 async signedUrl(path:string,download=false){const{data,error}=await supabase.storage.from("student-documents").createSignedUrl(path,300,{download});if(error)throw error;return data.signedUrl},
};
