import { supabase } from"../lib/supabase";
export interface InvoiceRecord{id:string;invoiceNo:string;receiptNo:string;studentCode:string;studentName:string;studentEmail:string;studentPhone:string;course:string;serviceCategory:string;coaIncomeCode:string;coaAssetCode:string;subtotal:number;discount:number;grandTotal:number;amountReceived:number;balance:number;amountInWords:string;paymentMethod:string;status:"PAID"|"PENDING"|"PARTIAL";date:string}
export interface JournalEntry{id:string;voucherNo:string;date:string;referenceNo:string;description:string;debitAccountCode:string;debitAccountName:string;creditAccountCode:string;creditAccountName:string;amount:number;preparedBy:string;status:"POSTED"}
export interface UniversityCommission{id:string;agreementNo:string;universityName:string;country:string;studentName:string;studentCode:string;commissionType:"Percentage"|"Fixed Amount";ratePct:number;tuitionFeeAudNpr:number;commissionDueNpr:number;receivedNpr:number;status:"PENDING"|"RECEIVED"|"OVERDUE";dueDate:string}
export function numberToWords(num:number){return `${Math.floor(num).toLocaleString("en-IN")} Nepalese Rupees Only`}
type InvoiceRow={id:string;invoice_no:string;course:string;service_category:string;income_account_code:string;subtotal:number;discount:number;grand_total:number;status:InvoiceRecord["status"];created_at:string;students?:{student_code:string;full_name:string;email:string;whatsapp:string}|null;finance_receipts?:Array<{receipt_no:string;amount:number;payment_method:string;asset_account_code:string}>};
export const FinanceService={
 async getInvoices():Promise<InvoiceRecord[]>{const{data,error}=await supabase.from("finance_invoices").select("*,students(student_code,full_name,email,whatsapp),finance_receipts(receipt_no,amount,payment_method,asset_account_code)").order("created_at",{ascending:false});if(error)throw error;return((data??[])as unknown as InvoiceRow[]).map(i=>{const r=i.finance_receipts?.[0],received=(i.finance_receipts??[]).reduce((s,x)=>s+Number(x.amount),0);return{id:i.id,invoiceNo:i.invoice_no,receiptNo:r?.receipt_no??"—",studentCode:i.students?.student_code??"—",studentName:i.students?.full_name??"Unknown",studentEmail:i.students?.email??"",studentPhone:i.students?.whatsapp??"",course:i.course,serviceCategory:i.service_category,coaIncomeCode:i.income_account_code,coaAssetCode:r?.asset_account_code??"1111",subtotal:Number(i.subtotal),discount:Number(i.discount),grandTotal:Number(i.grand_total),amountReceived:received,balance:Number(i.grand_total)-received,amountInWords:numberToWords(received||Number(i.grand_total)),paymentMethod:r?.payment_method??"Not paid",status:i.status,date:new Date(i.created_at).toLocaleDateString("en-GB")}})},
 async getJournals():Promise<JournalEntry[]>{const{data,error}=await supabase.from("finance_journals").select("*,finance_journal_lines(account_code,debit,credit),staff_profiles!finance_journals_prepared_by_fkey(full_name)").eq("status","POSTED").order("created_at",{ascending:false});if(error)throw error;return(data??[]).map(j=>{const lines=j.finance_journal_lines??[],d=lines.find((x:{debit:number})=>Number(x.debit)>0),c=lines.find((x:{credit:number})=>Number(x.credit)>0);return{id:j.id,voucherNo:j.voucher_no,date:new Date(j.created_at).toLocaleDateString("en-GB"),referenceNo:j.reference_no,description:j.description,debitAccountCode:d?.account_code??"",debitAccountName:d?.account_code??"",creditAccountCode:c?.account_code??"",creditAccountName:c?.account_code??"",amount:Number(d?.debit??0),preparedBy:j.staff_profiles?.full_name??"System",status:"POSTED"as const}})},
 async getCommissions():Promise<UniversityCommission[]>{const{data,error}=await supabase.from("university_commissions").select("*,students(student_code,full_name)").order("created_at",{ascending:false});if(error)throw error;return(data??[]).map(c=>({id:c.id,agreementNo:c.agreement_no,universityName:c.university_name,country:c.country,studentName:c.students?.full_name??"Unknown",studentCode:c.students?.student_code??"—",commissionType:c.commission_type as UniversityCommission["commissionType"],ratePct:Number(c.rate_pct),tuitionFeeAudNpr:Number(c.tuition_fee_npr),commissionDueNpr:Number(c.commission_due_npr),receivedNpr:Number(c.received_npr),status:c.status as UniversityCommission["status"],dueDate:c.due_date}))},
 async createInvoice(payload:{studentCode:string;studentName:string;studentEmail:string;studentPhone:string;course:string;serviceCategory:string;coaIncomeCode:string;paymentMethod:string;subtotal:number;discount:number;amountReceived:number;status:"PAID"|"PENDING"|"PARTIAL"}){const{data,error}=await supabase.rpc("issue_student_invoice",{payload:{student_code:payload.studentCode,course:payload.course,service_category:payload.serviceCategory,income_account_code:payload.coaIncomeCode,payment_method:payload.paymentMethod,subtotal:payload.subtotal,discount:payload.discount,amount_received:payload.amountReceived}});if(error)throw error;const invoices=await this.getInvoices();return invoices.find(i=>i.id===data.id)??invoices[0]},
 async createCommissionAgreement(payload:Omit<UniversityCommission,"id"|"agreementNo"|"commissionDueNpr"|"receivedNpr"|"status">){const{error}=await supabase.rpc("create_commission",{payload:{student_code:payload.studentCode,university_name:payload.universityName,country:payload.country,commission_type:payload.commissionType,rate_pct:payload.ratePct,tuition_fee_npr:payload.tuitionFeeAudNpr,due_date:payload.dueDate}});if(error)throw error;return(await this.getCommissions())[0]},
};
