import { supabase } from "../lib/supabase";
export interface MockTestResult{id:string;testCode:string;candidateType:"INTERNAL"|"EXTERNAL";studentName:string;studentCode:string;phone?:string;email?:string;testType:"IELTS Academic"|"PTE Academic"|"Duolingo (DET)"|"German A1"|"JLPT N5"|"TOEFL iBT";testDate:string;venue:string;examiner:string;listening:string|number;reading:string|number;writing:string|number;speaking:string|number;overallScore:string;status:"Score Issued"|"Pending Evaluation"|"Absent"|"Scheduled";examinerFeedback:string;targetAchieved:boolean;createdAt:string}
export interface MockTestSlot{id:string;title:string;testType:"IELTS Academic"|"PTE Academic"|"Duolingo (DET)"|"German A1"|"JLPT N5";date:string;time:string;room:string;invigilator:string;bookedSeats:number;totalSeats:number;status:"OPEN"|"FULL"|"COMPLETED"}
type ResultRow={id:string;test_code:string;candidate_type?:"INTERNAL"|"EXTERNAL";external_candidate_name?:string|null;external_phone?:string|null;external_email?:string|null;test_type:MockTestResult["testType"];test_date:string;venue:string;examiner:string;listening:number|null;reading:number|null;writing:number|null;speaking:number|null;overall_score:string;status:MockTestResult["status"];examiner_feedback:string|null;target_achieved:boolean;created_at:string;class_students?:{student_code:string;full_name:string}|null};
const serviceError=(error:{message?:string;details?:string;hint?:string}|null,fallback:string)=>new Error(error?.message||error?.details||error?.hint||fallback);
export const MockTestService={
 async getResults():Promise<MockTestResult[]>{const{data,error}=await supabase.from("mock_test_results").select("*,class_students(student_code,full_name)").order("test_date",{ascending:false});if(error)throw serviceError(error,"Unable to load mock results");return((data??[])as unknown as ResultRow[]).map(r=>({id:r.id,testCode:r.test_code,candidateType:r.candidate_type??"INTERNAL",studentName:r.class_students?.full_name??r.external_candidate_name??"Unknown",studentCode:r.class_students?.student_code??"External walk-in",phone:r.external_phone??undefined,email:r.external_email??undefined,testType:r.test_type,testDate:r.test_date,venue:r.venue,examiner:r.examiner,listening:r.listening??"—",reading:r.reading??"—",writing:r.writing??"—",speaking:r.speaking??"—",overallScore:r.overall_score,status:r.status,examinerFeedback:r.examiner_feedback??"",targetAchieved:r.target_achieved,createdAt:r.created_at.slice(0,10)}))},
 async getSlots():Promise<MockTestSlot[]>{const{data,error}=await supabase.from("mock_test_slots").select("*,mock_test_bookings(count)").order("test_date");if(error)throw serviceError(error,"Unable to load mock slots");return(data??[]).map(s=>({id:s.id,title:s.title,testType:s.test_type as MockTestSlot["testType"],date:s.test_date,time:s.test_time,room:s.room,invigilator:s.invigilator,bookedSeats:Number(s.mock_test_bookings?.[0]?.count??0),totalSeats:s.total_seats,status:s.status as MockTestSlot["status"]}))},
 async createResult(res:Omit<MockTestResult,"id"|"testCode"|"createdAt">){const{error}=await supabase.rpc("create_mock_result",{payload:{candidate_type:res.candidateType,student_code:res.studentCode,external_candidate_name:res.studentName,external_phone:res.phone??"",external_email:res.email??"",test_type:res.testType,test_date:res.testDate,venue:res.venue||"AECS Test Centre",examiner:res.examiner,listening:String(res.listening),reading:String(res.reading),writing:String(res.writing),speaking:String(res.speaking),overall_score:res.overallScore,status:res.status,examiner_feedback:res.examinerFeedback,target_achieved:res.targetAchieved}});if(error)throw serviceError(error,"Unable to save mock result");return res},
 async updateResult(id:string,res:Omit<MockTestResult,"id"|"testCode"|"createdAt">){const{error}=await supabase.rpc("update_mock_result",{result_uuid:id,payload:{test_type:res.testType,test_date:res.testDate,venue:res.venue,examiner:res.examiner,listening:String(res.listening),reading:String(res.reading),writing:String(res.writing),speaking:String(res.speaking),overall_score:res.overallScore,status:res.status,examiner_feedback:res.examinerFeedback,target_achieved:res.targetAchieved,external_candidate_name:res.studentName,external_phone:res.phone??"",external_email:res.email??""}});if(error)throw serviceError(error,"Unable to update mock result")},
 async createSlot(slot:Omit<MockTestSlot,"id">){const{error}=await supabase.rpc("create_mock_slot",{payload:{title:slot.title,test_type:slot.testType,date:slot.date,time:slot.time,room:slot.room,invigilator:slot.invigilator,total_seats:slot.totalSeats,status:slot.status}});if(error)throw serviceError(error,"Unable to schedule mock slot");return slot},
 async bookCandidate(slotId:string,candidate:{type:"INTERNAL"|"EXTERNAL";classStudentId?:string;name?:string;phone?:string;email?:string}){const{error}=await supabase.rpc("book_mock_candidate_v2",{payload:{slot_id:slotId,candidate_type:candidate.type,class_student_id:candidate.classStudentId??null,external_candidate_name:candidate.name??"",external_phone:candidate.phone??"",external_email:candidate.email??""}});if(error)throw serviceError(error,"Unable to book candidate")},
};
