import { supabase } from "../lib/supabase";
export interface MockTestResult{id:string;testCode:string;studentName:string;studentCode:string;testType:"IELTS Academic"|"PTE Academic"|"Duolingo (DET)"|"German A1"|"JLPT N5"|"TOEFL iBT";testDate:string;venue:string;examiner:string;listening:string|number;reading:string|number;writing:string|number;speaking:string|number;overallScore:string;status:"Score Issued"|"Pending Evaluation"|"Absent"|"Scheduled";examinerFeedback:string;targetAchieved:boolean;createdAt:string}
export interface MockTestSlot{id:string;title:string;testType:"IELTS Academic"|"PTE Academic"|"Duolingo (DET)"|"German A1"|"JLPT N5";date:string;time:string;room:string;invigilator:string;bookedSeats:number;totalSeats:number;status:"OPEN"|"FULL"|"COMPLETED"}
type ResultRow={id:string;test_code:string;test_type:MockTestResult["testType"];test_date:string;venue:string;examiner:string;listening:number|null;reading:number|null;writing:number|null;speaking:number|null;overall_score:string;status:MockTestResult["status"];examiner_feedback:string|null;target_achieved:boolean;created_at:string;class_students?:{student_code:string;full_name:string}|null};
export const MockTestService={
 async getResults():Promise<MockTestResult[]>{const{data,error}=await supabase.from("mock_test_results").select("*,class_students(student_code,full_name)").order("test_date",{ascending:false});if(error)throw error;return((data??[])as unknown as ResultRow[]).map(r=>({id:r.id,testCode:r.test_code,studentName:r.class_students?.full_name??"Unknown",studentCode:r.class_students?.student_code??"—",testType:r.test_type,testDate:r.test_date,venue:r.venue,examiner:r.examiner,listening:r.listening??"—",reading:r.reading??"—",writing:r.writing??"—",speaking:r.speaking??"—",overallScore:r.overall_score,status:r.status,examinerFeedback:r.examiner_feedback??"",targetAchieved:r.target_achieved,createdAt:r.created_at.slice(0,10)}))},
 async getSlots():Promise<MockTestSlot[]>{const{data,error}=await supabase.from("mock_test_slots").select("*").order("test_date");if(error)throw error;return(data??[]).map(s=>({id:s.id,title:s.title,testType:s.test_type as MockTestSlot["testType"],date:s.test_date,time:s.test_time,room:s.room,invigilator:s.invigilator,bookedSeats:0,totalSeats:s.total_seats,status:s.status as MockTestSlot["status"]}))},
 async createResult(res:Omit<MockTestResult,"id"|"testCode"|"createdAt">){const{error}=await supabase.rpc("create_mock_result",{payload:{student_code:res.studentCode,test_type:res.testType,test_date:res.testDate,venue:res.venue,examiner:res.examiner,listening:String(res.listening),reading:String(res.reading),writing:String(res.writing),speaking:String(res.speaking),overall_score:res.overallScore,status:res.status,examiner_feedback:res.examinerFeedback,target_achieved:res.targetAchieved}});if(error)throw error;return res},
 async createSlot(slot:Omit<MockTestSlot,"id">){const{error}=await supabase.rpc("create_mock_slot",{payload:{title:slot.title,test_type:slot.testType,date:slot.date,time:slot.time,room:slot.room,invigilator:slot.invigilator,total_seats:slot.totalSeats,status:slot.status}});if(error)throw error;return slot},
};
