import { supabase } from "../lib/supabase";

export interface StudentPayload { id?:string; code?:string; fullName:string; email:string; phone:string; dob:string; gender:"Male"|"Female"|"Other"; address?:string; targetCountry:string; secondCountry?:string; targetCourse:string; targetIntake?:string; budget?:string; counsellor?:string; status?:string; highestQualification?:string; academicStatus?:string; latestResult?:string; studyGap?:string; employmentStatus?:string; testTaken?:boolean; testType?:string; testScore?:string; hasPassport?:boolean; leadSource?:string; message?:string }
export interface StudentDirectoryRecord {id:string;code:string;student_code:string;fullName:string;full_name:string;email:string;phone:string;whatsapp:string;dob:string;gender:"Male"|"Female"|"Other";address:string;status:"NEW_LEAD"|"COUNSELLING"|"APPLICATION_SUBMITTED"|"OFFER_RECEIVED"|"VISA_PROCESSING"|"ENROLLED";targetCountry:string;secondCountry:string;targetCourse:string;targetIntake:string;budget:string;counsellor:string;englishTest:{taken:boolean;test:string;score:string};highestQualification:string;academicStatus:string;latestResult:string;studyGap:string;employmentStatus:string;academicSummary:string;hasPassport:boolean;leadSource:string;message:string;documentsVerified:number;documentsTotal:number;notes:string[];createdAt:string}
export interface LeadRecord {
  id:string; leadCode:string; fullName:string; email:string; phone:string;
  source:"Facebook / Instagram Ads"|"Google Search"|"Walk-in Inquiry"|"Education Fair 2026"|"Student Referral"|"TikTok / Social";
  targetCountry:"UK"|"Australia"|"Canada"|"USA"|"Germany"|"New Zealand"; targetCourse:string; targetIntake:string;
  budgetEstimate:string; assignedCounsellor:string; assignedCounsellorId?:string;
  stage:"NEW_INQUIRY"|"CONTACTED"|"COUNSELLING_SCHEDULED"|"HOT_PROSPECT"|"CONVERTED"|"LOST";
  priority:"HIGH"|"MEDIUM"|"LOW"; lastContactDate:string; notes:string[]; followUps:Array<{id:string;dueAt:string;note:string;completedAt:string|null}>; createdAt:string;
}
type LeadRow={id:string;lead_code:string;full_name:string;email:string|null;phone:string;source:LeadRecord["source"];target_country:LeadRecord["targetCountry"];target_course:string|null;target_intake:string|null;budget_estimate:string|null;assigned_counsellor:string|null;stage:LeadRecord["stage"];priority:LeadRecord["priority"];last_contact_at:string|null;created_at:string;staff_profiles?:{full_name:string}|null;lead_activities?:Array<{body:string|null;created_at:string}>;lead_follow_ups?:Array<{id:string;due_at:string;note:string;completed_at:string|null}>};
const friendlyDate=(value:string|null)=>value?new Intl.DateTimeFormat("en-NP",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kathmandu"}).format(new Date(value)):"Not contacted";
const mapLead=(row:LeadRow):LeadRecord=>({id:row.id,leadCode:row.lead_code,fullName:row.full_name,email:row.email??"",phone:row.phone,source:row.source,targetCountry:row.target_country,targetCourse:row.target_course??"Undecided",targetIntake:row.target_intake??"Undecided",budgetEstimate:row.budget_estimate??"Not provided",assignedCounsellor:row.staff_profiles?.full_name??"Unassigned",assignedCounsellorId:row.assigned_counsellor??undefined,stage:row.stage,priority:row.priority,lastContactDate:friendlyDate(row.last_contact_at),notes:(row.lead_activities??[]).filter(a=>a.body).map(a=>`[${friendlyDate(a.created_at)}] ${a.body}`),followUps:(row.lead_follow_ups??[]).map(f=>({id:f.id,dueAt:f.due_at,note:f.note,completedAt:f.completed_at})),createdAt:friendlyDate(row.created_at)});
type StudentRow={id:string;student_code:string;full_name:string|null;email:string|null;whatsapp:string|null;dob:string|null;gender:string|null;current_address:string|null;status:string;created_at:string;study_preferences?:{preferred_country:string|null;second_country:string|null;preferred_course:string|null;preferred_intake:string|null;budget:number|null}|null;academic_information?:{highest_qualification:string|null;current_status:string|null;latest_result:string|null;study_gap:string|null;employment_status:string|null}|null;english_tests?:{test_taken:boolean;test_type:string|null;score:string|null}|null;passport_information?:{has_passport:boolean}|null;additional_information?:{lead_source:string|null;message:string|null}|null;documents?:Array<{status:string}>;staff_profiles?:{full_name:string}|null};
const STATUS_MAP:Record<string,StudentDirectoryRecord["status"]>={NEW_LEAD:"NEW_LEAD",COUNSELLING_PENDING:"COUNSELLING",COUNSELLING_COMPLETED:"COUNSELLING",COUNSELLING:"COUNSELLING",APPLICATION_STARTED:"APPLICATION_SUBMITTED",APPLICATION_SUBMITTED:"APPLICATION_SUBMITTED",OFFER_RECEIVED:"OFFER_RECEIVED",VISA_PROCESSING:"VISA_PROCESSING",COMPLETED:"ENROLLED",ENROLLED:"ENROLLED",CONVERTED_TO_STUDENT:"COUNSELLING",CLOSED_LEAD:"NEW_LEAD"};
const directoryStatus=(status:string):StudentDirectoryRecord["status"]=>STATUS_MAP[status]??"NEW_LEAD";
const mapStudent=(row:StudentRow):StudentDirectoryRecord=>{const preference=row.study_preferences;const academic=row.academic_information;const test=row.english_tests;const extra=row.additional_information;const documents=row.documents??[];const code=row.student_code??"—";const fullName=row.full_name?.trim()||"Unnamed student";const phone=row.whatsapp?.trim()||"";return{id:row.id,code,student_code:code,fullName,full_name:fullName,email:row.email?.trim()||"",phone,whatsapp:phone,dob:row.dob??"",gender:row.gender==="Male"||row.gender==="Female"?row.gender:"Other",address:row.current_address??"",status:directoryStatus(row.status),targetCountry:preference?.preferred_country??"Undecided",secondCountry:preference?.second_country??"",targetCourse:preference?.preferred_course??"Undecided",targetIntake:preference?.preferred_intake??"Undecided",budget:preference?.budget?String(preference.budget):"",counsellor:row.staff_profiles?.full_name??"Unassigned",englishTest:{taken:Boolean(test?.test_taken),test:test?.test_taken?(test.test_type??"Test recorded"):"Not taken",score:test?.test_taken?(test.score??"Pending score"):"—"},highestQualification:academic?.highest_qualification??"",academicStatus:academic?.current_status??"",latestResult:academic?.latest_result??"",studyGap:academic?.study_gap??"",employmentStatus:academic?.employment_status??"",academicSummary:[academic?.highest_qualification,academic?.current_status,academic?.latest_result].filter(Boolean).join(" · ")||"Academic details not provided",hasPassport:Boolean(row.passport_information?.has_passport),leadSource:extra?.lead_source??"",message:extra?.message??"",documentsVerified:documents.filter(document=>document.status==="APPROVED").length,documentsTotal:10,notes:[],createdAt:row.created_at}};

export const StudentService={
  async getStudents():Promise<StudentDirectoryRecord[]>{const{data,error}=await supabase.from("students").select("id,student_code,full_name,email,whatsapp,dob,gender,current_address,status,created_at,study_preferences(preferred_country,second_country,preferred_course,preferred_intake,budget),academic_information(highest_qualification,current_status,latest_result,study_gap,employment_status),english_tests(test_taken,test_type,score),passport_information(has_passport),additional_information(lead_source,message),documents(status),staff_profiles!students_assigned_counsellor_fkey(full_name)").order("created_at",{ascending:false});if(error)throw error;return((data??[])as unknown as StudentRow[]).map(mapStudent)},
  async createStudent(payload:StudentPayload){const{data,error}=await supabase.rpc("register_student",{payload:{full_name:payload.fullName,email:payload.email,whatsapp:payload.phone,dob:payload.dob,gender:payload.gender,current_address:payload.address??"",preferred_country:payload.targetCountry,second_country:payload.secondCountry??"",preferred_course:payload.targetCourse,preferred_intake:payload.targetIntake??"Undecided",budget:(payload.budget??"").replace(/[^0-9.]/g,""),highest_qualification:payload.highestQualification??"To be assessed",current_status:payload.academicStatus??"Prospective student",latest_result:payload.latestResult??"",study_gap:payload.studyGap??"",employment_status:payload.employmentStatus??"",test_taken:Boolean(payload.testTaken),test_type:payload.testType??"",score:payload.testScore??"",has_passport:Boolean(payload.hasPassport),lead_source:payload.leadSource??"Staff entry",message:payload.message??""}});if(error)throw error;return{...data,code:data.student_code}},
  async updateStudent(studentId:string,payload:StudentPayload){const{error}=await supabase.rpc("update_student_record",{student_uuid:studentId,payload:{full_name:payload.fullName,email:payload.email,whatsapp:payload.phone,dob:payload.dob,gender:payload.gender,current_address:payload.address??"",preferred_country:payload.targetCountry,second_country:payload.secondCountry??"",preferred_course:payload.targetCourse,preferred_intake:payload.targetIntake??"",budget:(payload.budget??"").replace(/[^0-9.]/g,""),highest_qualification:payload.highestQualification??"",current_status:payload.academicStatus??"",latest_result:payload.latestResult??"",study_gap:payload.studyGap??"",employment_status:payload.employmentStatus??"",test_taken:Boolean(payload.testTaken),test_type:payload.testType??"",score:payload.testScore??"",has_passport:Boolean(payload.hasPassport),lead_source:payload.leadSource??"",message:payload.message??""}});if(error)throw error;const records=await this.getStudents();const saved=records.find(record=>record.id===studentId);if(payload.testTaken&&(!saved?.englishTest.taken||saved.englishTest.test!==payload.testType||saved.englishTest.score!==payload.testScore))throw new Error("The student was updated, but the English test record was not saved. Apply the latest student editor database migration and try again.");return records},
  async updateStatus(studentId:string,status:string){const{error}=await supabase.from("students").update({status}).eq("id",studentId);if(error)throw error;return this.getStudents()},
  async deleteStudent(studentId:string){const{error}=await supabase.from("students").delete().eq("id",studentId);if(error)throw error;return this.getStudents()},
};

export const LeadService={
  async getLeads():Promise<LeadRecord[]>{const{data,error}=await supabase.from("leads").select("*, staff_profiles!leads_assigned_counsellor_fkey(full_name), lead_activities(body,created_at), lead_follow_ups(id,due_at,note,completed_at)").order("created_at",{ascending:false}).order("created_at",{referencedTable:"lead_activities",ascending:false}).order("due_at",{referencedTable:"lead_follow_ups",ascending:true});if(error)throw error;return((data??[])as unknown as LeadRow[]).map(mapLead)},
  async createLead(payload:Omit<LeadRecord,"id"|"leadCode"|"createdAt"|"lastContactDate"|"notes"|"followUps">){const{data,error}=await supabase.rpc("create_lead",{payload:{full_name:payload.fullName,email:payload.email,phone:payload.phone,source:payload.source,target_country:payload.targetCountry,target_course:payload.targetCourse,target_intake:payload.targetIntake,budget_estimate:payload.budgetEstimate,assigned_counsellor:payload.assignedCounsellorId??"",stage:payload.stage,priority:payload.priority}});if(error)throw error;return data as{id:string;lead_code:string}},
  async updateLeadStage(leadId:string,stage:LeadRecord["stage"]){const{error}=await supabase.rpc("update_lead_stage",{lead_uuid:leadId,next_stage:stage});if(error)throw error},
  async addNote(leadId:string,note:string){const{error}=await supabase.rpc("add_lead_note",{lead_uuid:leadId,note});if(error)throw error},
  async scheduleFollowUp(leadId:string,dueAt:string,note:string){const{error}=await supabase.rpc("schedule_lead_follow_up",{lead_uuid:leadId,due_at:new Date(dueAt).toISOString(),follow_up_note:note});if(error)throw error},
  async completeFollowUp(followUpId:string){const{error}=await supabase.rpc("complete_lead_follow_up",{follow_up_uuid:followUpId});if(error)throw error},
  async convertLeadToStudent(lead:LeadRecord,profile:{dob:string;gender:string;highestQualification:string;currentAddress:string}){const{data,error}=await supabase.rpc("convert_lead",{lead_uuid:lead.id,student_payload:{dob:profile.dob,gender:profile.gender,current_address:profile.currentAddress,second_country:"",budget:"",highest_qualification:profile.highestQualification,current_status:"Prospective student",latest_result:"Pending assessment",study_gap:"",employment_status:"",test_taken:false,has_passport:false,message:"Converted from lead pipeline"}});if(error)throw error;return{...data,code:data.student_code}as{id:string;code:string;student_code:string}},
};
