import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const sql = readFileSync("supabase/migrations/202608210018_phase8_communications.sql", "utf8");
const groups = readFileSync("supabase/migrations/202608300001_single_office_staff_groups.sql", "utf8");
const messages = readFileSync("src/services/messagingService.ts", "utf8");
const messageUi = readFileSync("src/features/messages/MessagesWorkspace.tsx", "utf8");
const email = readFileSync("src/services/emailAutomationService.ts", "utf8");
const uuid = readFileSync("src/lib/generateUuid.ts", "utf8");
for (const table of ["communication_channels", "communication_channel_members", "communication_messages", "communication_reactions", "staff_notifications", "email_templates", "email_automations", "email_delivery_logs"]) assert.match(sql, new RegExp(`create table public\\.${table}\\b`));
for (const fn of ["send_internal_message", "toggle_message_reaction", "queue_email"]) assert.match(sql, new RegExp(`function public\\.${fn}`));
assert.match(sql, /alter publication supabase_realtime add table/);
assert.match(sql, /messages_participant_read/);
assert.match(messages, /supabase\.channel\(channelName\)/);
assert.match(messages, /crm-communications-\$\{generateUuid\(\)\}/);
assert.match(uuid, /typeof browserCrypto\.randomUUID === "function"/);
assert.match(uuid, /browserCrypto\.getRandomValues\(bytes\)/);
assert.match(messages, /send_internal_message/);
assert.doesNotMatch(messages, /localStorage|\/api\/sync/);
assert.match(groups, /function public\.create_staff_group/);
assert.match(groups, /communication_channel_members/);
assert.match(messages, /create_staff_group/);
assert.match(messageUi, /Create staff group/);
assert.match(email, /supabase\.rpc\("queue_email"/);
assert.match(email, /email_delivery_logs/);
console.log("Phase 8 communications checks passed.");
