import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const sql = readFileSync("supabase/migrations/202608210018_phase8_communications.sql", "utf8");
const groups = readFileSync("supabase/migrations/202608300001_single_office_staff_groups.sql", "utf8");
const messages = readFileSync("src/services/messagingService.ts", "utf8");
const messageUi = readFileSync("src/features/messages/MessagesWorkspace.tsx", "utf8");
const email = readFileSync("src/services/emailAutomationService.ts", "utf8");
const uuid = readFileSync("src/lib/generateUuid.ts", "utf8");
const calls = readFileSync("src/services/callingService.ts", "utf8");
const callMigration = readFileSync("supabase/migrations/202609110001_assignment_reports_voice_calls.sql", "utf8");
const notifier = readFileSync("src/components/common/GlobalMessageNotifier.tsx", "utf8");
const receiptSql = readFileSync("supabase/migrations/202609130001_conversation_read_receipts.sql", "utf8");
const supabaseClient = readFileSync("src/lib/supabase.ts", "utf8");
for (const table of ["communication_channels", "communication_channel_members", "communication_messages", "communication_reactions", "staff_notifications", "email_templates", "email_automations", "email_delivery_logs"]) assert.match(sql, new RegExp(`create table public\\.${table}\\b`));
for (const fn of ["send_internal_message", "toggle_message_reaction", "queue_email"]) assert.match(sql, new RegExp(`function public\\.${fn}`));
assert.match(sql, /alter publication supabase_realtime add table/);
assert.match(sql, /messages_participant_read/);
assert.match(messages, /supabase\.channel\(channelName\)/);
assert.match(messages, /crm-communications-\$\{generateUuid\(\)\}/);
assert.match(uuid, /typeof browserCrypto\.randomUUID === "function"/);
assert.match(uuid, /browserCrypto\.getRandomValues\(bytes\)/);
assert.match(messages, /send_internal_message/);
assert.doesNotMatch(messages, /localStorage|\/api\/sync/);
assert.match(groups, /function public\.create_staff_group/);
assert.match(groups, /communication_channel_members/);
assert.match(messages, /create_staff_group/);
assert.match(messageUi, /Create staff group/);
assert.doesNotMatch(messageUi, /handleStartVideoCall|Start HD Video Conference/);
assert.match(calls, /from\("staff_voice_calls"\)/);
assert.match(calls, /video: false/);
assert.doesNotMatch(calls, /fetch\("\/api\/sync\/call\/(start|answer|status|ice|end)/);
assert.match(callMigration, /create table if not exists public\.staff_voice_calls/);
assert.match(callMigration, /auth\.uid\(\) in\(caller_id,recipient_id\)/);
assert.match(notifier, /knownMessageIds/);
assert.match(notifier, /Notification\.permission===\"granted\"/);
assert.match(notifier, /unlockMessageAudio/);
assert.match(messages, /markConversationRead/);
assert.match(messages, /communication_message_reads\(read_at,staff_id\)/);
assert.match(messageUi, /formatSeenStatus/);
assert.match(messageUi, /Seen now/);
assert.match(receiptSql, /mark_conversation_messages_read/);
assert.match(receiptSql, /communication_message_reads_participants/);
assert.match(messages, /isReadByCurrentUser/);
assert.match(messages, /readCount/);
assert.match(messageUi, /Seen by/);
assert.match(supabaseClient, /mark_conversation_messages_read/);
assert.match(messages, /Asia\/Kathmandu/);
assert.match(messageUi, /lastMsg\.createdAt/);
assert.match(email, /supabase\.rpc\("queue_email"/);
assert.match(email, /email_delivery_logs/);
console.log("Phase 8 communications checks passed.");
