import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const sql = readFileSync("supabase/migrations/202608210019_phase9_reporting_administration.sql", "utf8");
const service = readFileSync("src/services/adminService.ts", "utf8");
const reportService = readFileSync("src/services/analyticsReportService.ts", "utf8");
const reportUi = readFileSync("src/features/analytics/AnalyticsDashboard.tsx", "utf8");
const dashboard = readFileSync("src/services/dashboardService.ts", "utf8");
const dashboardUi = readFileSync("src/features/dashboard/ManagementDashboard.tsx", "utf8");
for (const table of ["organizations", "branches", "report_definitions", "report_exports"]) assert.match(sql, new RegExp(`create table public\\.${table}`));
for (const view of ["report_lead_pipeline", "report_application_pipeline", "report_finance_summary", "report_staff_attendance"]) assert.match(sql, new RegExp(`view public\\.${view}`));
for (const fn of ["management_dashboard_summary", "save_organization", "request_report_export"]) assert.match(sql, new RegExp(`function public\\.${fn}`));
for (const table of ["leads", "university_applications", "study_preferences", "lead_follow_ups", "activity_logs", "audit_logs"]) assert.match(dashboard, new RegExp(`from\\(\"${table}\"\\)`));
assert.match(dashboard, /getOperationalData/);
assert.match(dashboardUi, /DashboardService\.getOperationalData/);
assert.doesNotMatch(dashboardUi, /const INTAKE_TREND_DATA/);
assert.match(sql, /audit_logs/);
assert.match(service, /save_organization/);
assert.match(reportService, /report_lead_pipeline/);
assert.match(reportService, /management_dashboard_summary/);
assert.match(reportUi, /Live Student Pipeline/);
assert.doesNotMatch(reportUi, /BLUEPRINT_50_REPORTS|1,200 leads|96\.2/);
console.log("Phase 9 reporting/admin checks passed.");
