import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
  const url=Deno.env.get("SUPABASE_URL")!,serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,authorization=req.headers.get("Authorization")||"";const admin=createClient(url,serviceKey,{auth:{persistSession:false}});const token=authorization.replace("Bearer ","");const{data:{user},error:userError}=await admin.auth.getUser(token);if(userError||!user)throw new Error("Unauthorized");const{data:actor}=await admin.from("staff_profiles").select("role,is_active").eq("id",user.id).single();if(!actor?.is_active||!["ADMIN","DIRECTOR"].includes(actor.role))throw new Error("Administrator access required");
  const body=await req.json();
  if(body.action==="set_password"){if(!body.user_id)throw new Error("Staff member is required");if(!body.password||body.password.length<10)throw new Error("Password must contain at least 10 characters");const{error}=await admin.auth.admin.updateUserById(body.user_id,{password:body.password});if(error)throw error;await admin.from("audit_logs").insert({user_id:user.id,action:"STAFF_PASSWORD_UPDATED",module:"staff",metadata:{staff_id:body.user_id}});return json({ok:true});}
  const allowed=["ADMIN","HR_ADMIN","DIRECTOR","FRONT_DESK","COUNSELLOR","DOCUMENTATION","FINANCE","TEST_BOOKING","SENIOR_COUNSELLOR","VISA_OFFICER","ACCOUNTANT","FACULTY","MARKETING","IT_ADMIN"];
  const modules=["dashboard","leads","students","counselling","applications","b2b","classes","mocks","documents","finance","reports","hrms","settings","messages"];
  if(!allowed.includes(body.role))throw new Error("Invalid role");if(!Array.isArray(body.desktop_modules)||body.desktop_modules.some((item:unknown)=>typeof item!=="string"||!modules.includes(item)))throw new Error("Invalid desktop module selection");
  const accessMode=body.access_mode==="EXACT"?"EXACT":"ROLE_PLUS";
  const permissionOverrides=Array.isArray(body.permission_overrides)?[...new Set(body.permission_overrides.filter((item:unknown)=>typeof item==="string"&&/^[a-z_]+\.[a-z_]+$/.test(item as string)))]:[];
  const inactivityMinutes=Number(body.inactivity_minutes||30);if(!Number.isInteger(inactivityMinutes)||inactivityMinutes<5||inactivityMinutes>720)throw new Error("Invalid inactivity timeout");
  const profile={full_name:body.full_name?.trim(),email:body.email?.trim().toLowerCase(),role:body.role,job_title:body.job_title?.trim()||"Staff Member",department:body.department?.trim()||"General Operations",branch:"AECS Bagbazar Main Office",phone:body.phone?.trim()||null,desktop_modules:body.desktop_modules,assigned_responsibilities:body.assigned_responsibilities?.trim()||"",access_mode:accessMode,inactivity_minutes:inactivityMinutes,is_active:body.is_active!==false};
  if(!profile.full_name||!profile.email)throw new Error("Name and email are required");
  const saveOverrides=async(staffId:string)=>{const{error:deleteError}=await admin.from("staff_permission_overrides").delete().eq("staff_id",staffId);if(deleteError)throw deleteError;if(permissionOverrides.length){const{error:insertError}=await admin.from("staff_permission_overrides").insert(permissionOverrides.map(permission_name=>({staff_id:staffId,permission_name,enabled:true,updated_by:user.id})));if(insertError)throw insertError;}};
  if(body.action==="update"){if(!body.user_id)throw new Error("Staff member is required");const{error}=await admin.from("staff_profiles").update(profile).eq("id",body.user_id);if(error)throw error;await admin.from("hr_employees").update({full_name:profile.full_name,email:profile.email,phone:profile.phone,job_title:profile.job_title,department:profile.department,branch:profile.branch,employment_status:profile.is_active?"ACTIVE":"SUSPENDED",updated_at:new Date().toISOString()}).eq("staff_profile_id",body.user_id);await saveOverrides(body.user_id);await admin.from("audit_logs").insert({user_id:user.id,action:"STAFF_ACCESS_UPDATED",module:"staff",metadata:{staff_id:body.user_id,role:body.role,access_mode:accessMode,permission_count:permissionOverrides.length}});return json({ok:true,user_id:body.user_id});}
  if(body.action!=="create")throw new Error("Invalid action");if(!body.password||body.password.length<10)throw new Error("Password must contain at least 10 characters");const{data:created,error:createError}=await admin.auth.admin.createUser({email:profile.email,password:body.password,email_confirm:true,user_metadata:{full_name:profile.full_name,role:profile.role}});if(createError)throw createError;const{error:profileError}=await admin.from("staff_profiles").upsert({id:created.user.id,...profile});if(profileError){await admin.auth.admin.deleteUser(created.user.id);throw profileError;}const{data:employee,error:employeeError}=await admin.from("hr_employees").upsert({staff_profile_id:created.user.id,full_name:profile.full_name,email:profile.email,phone:profile.phone,job_title:profile.job_title,department:profile.department,branch:profile.branch,join_date:new Date().toISOString().slice(0,10),employment_status:"ACTIVE",base_salary:0,created_by:user.id},{onConflict:"email"}).select("id").single();if(employeeError){await admin.auth.admin.deleteUser(created.user.id);throw employeeError;}await saveOverrides(created.user.id);await admin.from("audit_logs").insert({user_id:user.id,action:"STAFF_CREATED",module:"staff",metadata:{staff_id:created.user.id,employee_id:employee.id,role:body.role,desktop_modules:body.desktop_modules,access_mode:accessMode,permission_count:permissionOverrides.length}});return json({ok:true,user_id:created.user.id,employee_id:employee.id});
}catch(error){return json({error:error instanceof Error?error.message:"Unable to manage staff"},400)}});
