import { supabase } from "../../lib/supabase";import type{Student,StudentStatus}from"./student.types";
export type StudentFilters={search?:string;country?:string;status?:string;testType?:string;from?:string;to?:string;weekdays?:string[];page:number;pageSize:number};
export async function listStudents(f:StudentFilters){let q=supabase.from("students").select("id,student_code,full_name,whatsapp,email,status,created_at,assigned_counsellor,study_preferences(preferred_country,preferred_course),staff_profiles!students_assigned_counsellor_fkey(full_name)",{count:"exact"}).order("created_at",{ascending:false});if(f.search)q=q.or(`full_name.ilike.%${f.search}%,student_code.ilike.%${f.search}%,email.ilike.%${f.search}%,whatsapp.ilike.%${f.search}%`);if(f.status)q=q.eq("status",f.status);if(f.from)q=q.gte("created_at",f.from);if(f.to)q=q.lt("created_at",f.to);const calendarFilter=Boolean(f.weekdays?.length);const offset=(f.page-1)*f.pageSize;const{data,error,count}=await q.range(calendarFilter?0:offset,calendarFilter?4999:offset+f.pageSize-1);if(error)throw error;let rows=(data||[])as unknown as Student[];if(f.country)rows=rows.filter(s=>s.study_preferences?.preferred_country===f.country);if(f.testType&&rows.length){const ids=rows.map(s=>s.id);const{data:tests}=await supabase.from("english_tests").select("student_id,test_type,test_taken").in("student_id",ids);const allowed=new Set((tests||[]).filter(t=>f.testType==="None"?!t.test_taken:t.test_type===f.testType).map(t=>t.student_id));rows=rows.filter(s=>allowed.has(s.id))}if(calendarFilter){const formatter=new Intl.DateTimeFormat("en-US",{weekday:"long",timeZone:"Asia/Kathmandu"});rows=rows.filter(s=>f.weekdays!.includes(formatter.format(new Date(s.created_at))));const filteredCount=rows.length;return{data:rows.slice(offset,offset+f.pageSize),count:filteredCount}}return{data:rows,count:count||0}}
export async function getStudent(id:string){const{data,error}=await supabase.from("students").select("*,study_preferences(*),academic_information(*),english_tests(*),passport_information(*),additional_information(*),staff_profiles!students_assigned_counsellor_fkey(full_name)").eq("id",id).single();if(error)throw error;return data as unknown as Student}
export async function registerStudent(payload:Record<string,unknown>){const{data,error}=await supabase.rpc("register_student",{payload});if(error)throw error;return data as{student_code:string;id:string;status:string}}
export async function updateStudent(id:string,values:Partial<Student>){const{error}=await supabase.from("students").update(values).eq("id",id);if(error)throw error}
export async function deleteStudent(id:string){const{error}=await supabase.from("students").delete().eq("id",id);if(error)throw error}
export async function updateStatus(id:string,status:StudentStatus){await updateStudent(id,{status})}
export async function updateStudentRecord(id:string,payload:Record<string,unknown>){const{error}=await supabase.rpc("update_student_record",{student_uuid:id,payload});if(error)throw error}
