import{useEffect,useState}from"react";
import{ArrowLeft,BookOpenCheck,Mail,Phone,Printer}from"lucide-react";
import{Link,useParams}from"react-router-dom";
import{supabase}from"../../lib/supabase";

type Enquiry={id:string;enquiry_code:string;full_name:string;whatsapp:string;email:string;class_type:string;class_mode:string;current_level:string;needs_counselling:boolean;preferred_country:string|null;status:string;message:string|null;consented_at:string;created_at:string};
const statuses=["NEW_ENQUIRY","CONTACTED","TRIAL_SCHEDULED","ENROLLED","CLOSED"];
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase()).replace("Det","DET").replace("Pte","PTE").replace("Ielts","IELTS");

export function ClassEnquiryProfile(){const{id=""}=useParams(),[row,setRow]=useState<Enquiry|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{let live=true;setLoading(true);supabase.from("class_enquiries").select("*").eq("id",id).single().then(({data})=>{if(live){setRow(data as Enquiry|null);setLoading(false)}});return()=>{live=false}},[id]);async function status(value:string){await supabase.from("class_enquiries").update({status:value}).eq("id",id);setRow(current=>current?{...current,status:value}:current)}if(loading)return <div className="app-loader">Loading class enquiry…</div>;if(!row)return <section className="panel empty-profile"><BookOpenCheck/><h2>Class enquiry not found</h2><Link to="/class-enquiries">Return to class enquiries</Link></section>;return <><Link className="back-link" to="/class-enquiries"><ArrowLeft size={15}/>Back to class enquiries</Link><section className="profile-header panel class-profile-header"><div className="profile-identity"><div><BookOpenCheck size={25}/></div><section><span>{row.enquiry_code}</span><h2>{row.full_name}</h2><p>Received {new Date(row.created_at).toLocaleString()}</p></section></div><div className="profile-actions"><select value={row.status} onChange={event=>status(event.target.value)}>{statuses.map(value=><option value={value} key={value}>{label(value)}</option>)}</select><button className="secondary-button" onClick={()=>print()}><Printer size={16}/>Print</button></div></section><div className="class-profile-grid"><Info title="Contact information" rows={[["Full name",row.full_name],["Email",row.email],["WhatsApp",row.whatsapp]]}/><Info title="Class preference" rows={[["Class",label(row.class_type)],["Mode",label(row.class_mode)],["Current level",label(row.current_level)]]}/><Info title="Counselling request" rows={[["Counselling requested",row.needs_counselling?"Yes":"No"],["Preferred country",row.needs_counselling?row.preferred_country||"Not specified":"Not applicable"]]}/><section className="panel enquiry-message-card"><header><h3>Student message</h3><p>The additional note submitted with this enquiry.</p></header><blockquote>{row.message?.trim()||"No additional message was provided."}</blockquote></section><section className="panel enquiry-meta-card"><h3>Submission record</h3><div><span>Consent recorded</span><strong>{new Date(row.consented_at).toLocaleString()}</strong></div><div><span>Enquiry received</span><strong>{new Date(row.created_at).toLocaleString()}</strong></div><a href={`mailto:${row.email}`}><Mail size={15}/>Email student</a><a href={`https://wa.me/${row.whatsapp.replace(/\D/g,"")}`} target="_blank" rel="noreferrer"><Phone size={15}/>Open WhatsApp</a></section></div></>}
function Info({title,rows}:{title:string;rows:string[][]}){return <section className="panel info-section"><h3>{title}</h3><dl>{rows.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></section>}
