import { useMemo,useState } from "react";
import { BarChart3,Bookmark,CalendarDays,ChevronLeft,ChevronRight,Columns3,Download,Eye,FileDown,FileSpreadsheet,Filter,Printer,RefreshCw,Search,ShieldCheck,Star,TrendingUp,X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { AnalyticsReportService,type CatalogueReportResult,type ReportFilters } from "../../services/analyticsReportService";
import { REPORT_CATALOGUE,REPORT_COUNT,reportKey,type ReportCategory,type ReportGroup } from "./reportCatalogue";
import { notifyError,notifySuccess } from "../../components/common/CrmNotifications";

const groups:(ReportGroup|"All")[]=["All","CRM & Consultancy","Accounting & Finance","Control & Intelligence"];
const labels:Record<string,string>={source:"Record type",record_count:"Number of records",total_amount:"Financial value",created_at:"Added on",updated_at:"Last updated",document_name:"Document",document_type:"Document category",file_size:"File size",mime_type:"File format",user_id:"Changed by",action:"Activity",module:"CRM area",age_days:"Age (days)",rate_percent:"Rate",matching_records:"Successful records",total_records:"Total records"};
const sources:Record<string,string>={leads:"Leads and enquiries",students:"Student records",counselling_records:"Counselling sessions",university_applications:"University applications",visa_tracking:"Visa cases",documents:"Student documents",document_activity:"Document history",mock_test_bookings:"Test bookings",class_students:"Class students",test_prep_batches:"Class batches",batch_enrollments:"Batch enrolments",b2b_partners:"Education partners",student_invoices:"Student billing",finance_journals:"Accounting entries",finance_journal_lines:"Account transactions",chart_of_accounts:"Accounts",staff_assignments:"Staff assignments",case_tasks:"Application tasks",lead_follow_ups:"Lead follow-ups",communication_messages:"Staff messages",staff_voice_calls:"Voice calls",email_delivery_logs:"Email history",audit_logs:"System activity",report_exports:"Report exports",hr_tds_ledger:"Tax records"};
const hiddenByDefault=new Set(["id","user_id","student_id","sender_id","recipient_id","storage_path","metadata","created_by","updated_by","uploaded_by"]);
const title=(value:string)=>labels[value]??value.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase());
const prettyEnum=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,char=>char.toUpperCase());
const display=(value:unknown,column="")=>{if(value===null||value===undefined||value==="")return "Not recorded";if(column==="source")return sources[String(value).replaceAll(" ","_")]??prettyEnum(String(value));if(column==="file_size")return `${(Number(value)/1024).toLocaleString(undefined,{maximumFractionDigits:1})} KB`;if(column==="mime_type"){const type=String(value);return type.includes("pdf")?"PDF document":type.includes("image")?"Image":type.includes("word")?"Word document":prettyEnum(type.split("/").at(-1)??type)}if(column.includes("_at")||column.includes("date")){const date=new Date(String(value));if(!Number.isNaN(date.getTime()))return date.toLocaleString("en-GB",{dateStyle:"medium",timeStyle:column.includes("_at")?"short":undefined})}if(column==="rate_percent")return `${Number(value).toLocaleString()}%`;if(typeof value==="number")return value.toLocaleString();if(typeof value==="boolean")return value?"Yes":"No";if(typeof value==="object")return "Additional information available";const text=String(value);return /^[A-Z0-9_]+$/.test(text)?prettyEnum(text):text};
const csv=(value:unknown)=>`"${display(value).replaceAll('"','""')}"`;
const routes:Record<string,string>={leads:"/leads",students:"/students",counselling_records:"/students",university_applications:"/applications",visa_tracking:"/applications",documents:"/documents",mock_test_bookings:"/mock-tests",class_students:"/classes",test_prep_batches:"/classes",b2b_partners:"/b2b",student_invoices:"/finance",finance_journals:"/finance",finance_journal_lines:"/finance",chart_of_accounts:"/finance",staff_assignments:"/assignments",communication_messages:"/messages",audit_logs:"/settings"};
const reportDescription=(name:string)=>{const text=name.toLowerCase();if(text.includes("summary")||text.includes("dashboard"))return "A clear overview calculated from the latest CRM records.";if(text.includes("aging"))return "See how long open cases have been waiting and where follow-up is needed.";if(text.includes("conversion")||text.includes("rate"))return "Understand performance using current CRM outcomes and totals.";if(text.includes("country")||text.includes("source")||text.includes("status"))return `Compare ${text} using current CRM records.`;if(text.includes("master")||text.includes("register"))return "View the complete authorized list with the most useful details.";return `View current ${text} information in a simple, staff-friendly format.`};
function saveFile(content:string,type:string,name:string){const url=URL.createObjectURL(new Blob([content],{type}));const anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)}
function storedSet(key:string){try{return new Set<string>(JSON.parse(localStorage.getItem(key)??"[]"))}catch{return new Set<string>()}}

export function AnalyticsDashboard(){
 const navigate=useNavigate();
 const[group,setGroup]=useState<ReportGroup|"All">("All"),[search,setSearch]=useState(""),[activeCategory,setActiveCategory]=useState<number|null>(null);
 const[favorites,setFavorites]=useState(()=>storedSet("aecs_report_favorites")),[saved,setSaved]=useState(()=>storedSet("aecs_saved_reports"));
 const[result,setResult]=useState<CatalogueReportResult|null>(null),[loading,setLoading]=useState(""),[filters,setFilters]=useState<ReportFilters>({}),[draft,setDraft]=useState<ReportFilters>({}),[activeRow,setActiveRow]=useState<Record<string,unknown>|null>(null);
 const[visible,setVisible]=useState<Set<string>>(new Set()),[showColumns,setShowColumns]=useState(false),[sort,setSort]=useState<{column:string;direction:"asc"|"desc"}|null>(null),[page,setPage]=useState(1);
 const categories=useMemo(()=>REPORT_CATALOGUE.filter(item=>(group==="All"||item.group===group)&&`${item.name} ${item.description} ${item.reports.join(" ")}`.toLowerCase().includes(search.toLowerCase())),[group,search]);
 const selected=REPORT_CATALOGUE.find(item=>item.id===activeCategory)??null;
 const availableColumns=useMemo(()=>[...new Set((result?.rows??[]).flatMap(row=>Object.keys(row)))],[result]);
 const columns=useMemo(()=>availableColumns.filter(column=>visible.size?visible.has(column):!hiddenByDefault.has(column)&&column!=="mime_type"),[availableColumns,visible]);
 const rows=useMemo(()=>{const next=[...(result?.rows??[])];if(sort)next.sort((a,b)=>display(a[sort.column],sort.column).localeCompare(display(b[sort.column],sort.column),undefined,{numeric:true})*(sort.direction==="asc"?1:-1));return next},[result,sort]);
 const size=25,pages=Math.max(1,Math.ceil(rows.length/size)),shown=rows.slice((page-1)*size,page*size);
 const summaryView=rows.length>0&&rows.every(row=>"source" in row&&"record_count" in row);
 const run=async(category:ReportCategory,name:string,next=draft)=>{try{setLoading(reportKey(category.id,name));const generated=await AnalyticsReportService.runCatalogueReport(category.id,name,next);setResult(generated);setFilters(next);setDraft(next);setVisible(new Set());setSort(null);setPage(1)}catch(error){notifyError("Report unavailable",error instanceof Error?error.message:"Unable to generate report")}finally{setLoading("")}};
 const toggle=(key:string,value:string,current:Set<string>,update:(value:Set<string>)=>void)=>{const next=new Set(current);next.has(value)?next.delete(value):next.add(value);localStorage.setItem(key,JSON.stringify([...next]));update(next)};
 const exportRows=(format:"CSV"|"XLSX")=>{if(!result||!columns.length)return;const body=[columns.map(csv).join(","),...rows.map(row=>columns.map(column=>csv(display(row[column],column))).join(","))].join("\r\n");if(format==="CSV")saveFile(`\ufeff${body}`,"text/csv;charset=utf-8",`AECS_${result.key}.csv`);else saveFile(`<table><tr>${columns.map(c=>`<th>${title(c)}</th>`).join("")}</tr>${rows.map(row=>`<tr>${columns.map(c=>`<td>${display(row[c],c)}</td>`).join("")}</tr>`).join("")}</table>`,`application/vnd.ms-excel`,`AECS_${result.key}.xls`);void AnalyticsReportService.logExport(result.key,format,filters)};
 const print=()=>{if(result){void AnalyticsReportService.logExport(result.key,"PDF",filters);window.print()}};
 return <div className="page-container reports-centre">
  <header className="reports-hero"><div><span><BarChart3 size={15}/>AECS management intelligence</span><h2>Reports & Analytics Centre</h2><p>{REPORT_CATALOGUE.length} non-HRMS categories · {REPORT_COUNT} configured report views · CRM, finance, compliance and intelligence.</p></div><div className="reports-hero-badges"><b><ShieldCheck size={15}/>Role protected</b><b><RefreshCw size={15}/>Live sources</b></div></header>
  <section className="reports-summary"><article><TrendingUp/><span><strong>{REPORT_CATALOGUE.filter(x=>x.group==="CRM & Consultancy").length}</strong><small>CRM categories</small></span></article><article><FileSpreadsheet/><span><strong>{REPORT_CATALOGUE.filter(x=>x.group==="Accounting & Finance").length}</strong><small>Finance categories</small></span></article><article><ShieldCheck/><span><strong>{REPORT_CATALOGUE.filter(x=>x.group==="Control & Intelligence").length}</strong><small>Control categories</small></span></article><article><Star/><span><strong>{favorites.size}</strong><small>Favourites</small></span></article></section>
  <section className="reports-toolbar"><div className="reports-groups">{groups.map(item=><button type="button" className={group===item?"active":""} onClick={()=>{setGroup(item);setActiveCategory(null)}} key={item}>{item}</button>)}</div><label><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search every report…"/></label></section>
  <div className="reports-layout"><aside className="reports-category-list"><header><span>Report catalogue</span><b>{categories.length}</b></header>{categories.map(item=><button type="button" key={item.id} className={activeCategory===item.id?"active":""} onClick={()=>setActiveCategory(item.id)}><span>{String(item.id).padStart(2,"0")}</span><div><strong>{item.name}</strong><small>{item.reports.length} reports</small></div><ChevronRight size={15}/></button>)}</aside>
   <main className="reports-catalogue-panel">{selected?<><header><div><span>{selected.group} · Category {selected.id}</span><h3>{selected.name}</h3><p>{selected.description}</p></div><b>{selected.reports.length} reports</b></header><div className="reports-card-grid">{selected.reports.map(name=>{const key=reportKey(selected.id,name);return <article key={key}><div><span>{String(selected.id).padStart(2,"0")}</span><button type="button" className={favorites.has(key)?"is-favourite":""} onClick={()=>toggle("aecs_report_favorites",key,favorites,setFavorites)}><Star size={15}/></button></div><h4>{name}</h4><p>{reportDescription(name)}</p><footer>{saved.has(key)&&<span><Bookmark size={12}/>Saved</span>}<button type="button" onClick={()=>void run(selected,name)} disabled={loading===key}>{loading===key?<RefreshCw className="spin" size={14}/>:<Eye size={14}/>}Open report</button></footer></article>})}</div></>:<div className="reports-welcome"><BarChart3 size={38}/><h3>Select a report category</h3><p>Choose from the complete non-HRMS catalogue. HR reports remain in the dedicated HRMS Reports Centre.</p></div>}</main>
  </div>
  {result&&<div className="modal-backdrop-clean report-result-backdrop" onClick={()=>setResult(null)}><div className="report-result-sheet" onClick={e=>e.stopPropagation()}>
   <header className="report-result-header"><div><span>{result.categoryName}</span><h3>{result.name}</h3><p>Live CRM report · Updated {new Date(result.generatedAt).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})} · {result.rows.length.toLocaleString()} matching records</p></div><button onClick={()=>setResult(null)} aria-label="Close report"><X size={18}/></button></header>
   <section className="report-filter-bar"><label className="report-search-field"><span>Find a record</span><i><Search size={14}/><input value={draft.query??""} onChange={e=>setDraft({...draft,query:e.target.value})} placeholder="Name, code or keyword"/></i></label><label><span>From date</span><i><CalendarDays size={14}/><input type="date" value={draft.dateFrom??""} onChange={e=>setDraft({...draft,dateFrom:e.target.value})}/></i></label><label><span>To date</span><i><CalendarDays size={14}/><input type="date" value={draft.dateTo??""} onChange={e=>setDraft({...draft,dateTo:e.target.value})}/></i></label><label><span>Destination</span><input value={draft.country??""} onChange={e=>setDraft({...draft,country:e.target.value})} placeholder="All countries"/></label><label><span>Record status</span><input value={draft.status??""} onChange={e=>setDraft({...draft,status:e.target.value})} placeholder="All statuses"/></label><button className="btn-primary" onClick={()=>{const category=REPORT_CATALOGUE.find(x=>x.id===result.categoryId);if(category)void run(category,result.name,draft)}}><Filter size={14}/>Update report</button></section>
   <section className="report-action-bar"><div><button onClick={()=>toggle("aecs_report_favorites",result.key,favorites,setFavorites)}><Star size={14}/>Favourite</button><button onClick={()=>{toggle("aecs_saved_reports",result.key,saved,setSaved);notifySuccess("Saved report updated","Your report preference was saved.")}}><Bookmark size={14}/>Save</button><button onClick={()=>setShowColumns(!showColumns)}><Columns3 size={14}/>Columns</button></div><div><button onClick={()=>exportRows("CSV")}><Download size={14}/>CSV</button><button onClick={()=>exportRows("XLSX")}><FileDown size={14}/>Excel</button><button onClick={print}><Printer size={14}/>Print / PDF</button></div>{showColumns&&<div className="report-column-menu">{[...new Set(result.rows.flatMap(row=>Object.keys(row)))].map(column=><label key={column}><input type="checkbox" checked={visible.size===0||visible.has(column)} onChange={()=>setVisible(current=>{const next=current.size?new Set(current):new Set(result.rows.flatMap(row=>Object.keys(row)));next.has(column)?next.delete(column):next.add(column);return next})}/><span>{title(column)}</span></label>)}</div>}</section>
   <div className="report-data-table">{result.rows.length?(summaryView?<div className="report-readable-summary">{shown.map((row,index)=><article key={String(row.source??index)}><div><span>{display(row.source,"source")}</span><small>Live CRM records</small></div><strong>{display(row.record_count,"record_count")}</strong><p>{Number(row.record_count)===1?"record available":"records available"}</p>{row.total_amount!==undefined&&<em>Recorded value: {display(row.total_amount,"total_amount")}</em>}<button onClick={()=>setActiveRow(row)}>View records <ChevronRight size={14}/></button></article>)}</div>:<table className="crm-table"><thead><tr>{columns.map(column=><th key={column}><button onClick={()=>setSort(current=>({column,direction:current?.column===column&&current.direction==="asc"?"desc":"asc"}))}>{title(column)}{sort?.column===column?<small>{sort.direction==="asc"?"▲":"▼"}</small>:null}</button></th>)}<th>Details</th></tr></thead><tbody>{shown.map((row,index)=><tr key={String(row.id??`${page}-${index}`)}>{columns.map(column=><td key={column}>{display(row[column],column)}</td>)}<td><button className="report-view-details" onClick={()=>setActiveRow(row)}><Eye size={13}/>View details</button></td></tr>)}</tbody></table>):<div className="report-empty"><FileSpreadsheet size={30}/><h4>No records match this report</h4><p>Try changing the filters. New CRM activity will appear here automatically.</p></div>}</div>
   <footer className="report-pagination"><span>Showing {rows.length?(page-1)*size+1:0}–{Math.min(page*size,rows.length)} of {rows.length}</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}><ChevronLeft size={14}/></button><b>Page {page} of {pages}</b><button disabled={page===pages} onClick={()=>setPage(page+1)}><ChevronRight size={14}/></button></div></footer>
   {activeRow&&<aside className="report-row-details"><header><div><span>Record information</span><h4>{display(activeRow.document_name??activeRow.full_name??activeRow.name??activeRow.action??activeRow.source??"Report record",activeRow.source?"source":"")}</h4></div><button onClick={()=>setActiveRow(null)} aria-label="Close record details"><X size={16}/></button></header><div>{Object.entries(activeRow).filter(([key])=>!hiddenByDefault.has(key)).map(([key,value])=><dl key={key}><dt>{title(key)}</dt><dd>{display(value,key)}</dd></dl>)}</div><footer><button className="btn-secondary" onClick={()=>setActiveRow(null)}>Close</button><button className="btn-primary" onClick={()=>navigate(routes[String(activeRow.source??"").replaceAll(" ","_")]??"/dashboard")}>Open in CRM</button></footer></aside>}
  </div></div>}
 </div>
}
export default AnalyticsDashboard;
