import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BarChart3, Download, Eye, FileSpreadsheet, RefreshCw, Search, ShieldCheck, TrendingUp, Users, X } from "lucide-react";
import { AnalyticsReportService, type FunnelStage, type LiveReportDefinition, type LiveReportResult } from "../../services/analyticsReportService";
import { EmployeeMonthlyReport } from "./EmployeeMonthlyReport";

const pretty=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,letter=>letter.toUpperCase());
const displayValue=(value:unknown)=>value===null||value===undefined||value===""?"—":typeof value==="number"?value.toLocaleString():String(value);
const escapeCsv=(value:unknown)=>`"${displayValue(value).replace(/"/g,'""')}"`;

function downloadReport(result:LiveReportResult){const keys=[...new Set(result.rows.flatMap(row=>Object.keys(row)))];const csv=[keys.map(escapeCsv).join(","),...result.rows.map(row=>keys.map(key=>escapeCsv(row[key])).join(","))].join("\n");const url=URL.createObjectURL(new Blob([`\ufeff${csv}`],{type:"text/csv;charset=utf-8"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`AECS_${result.key}_${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url)}

export function AnalyticsDashboard(){
  const[activeTab,setActiveTab]=useState<"reports"|"employees"|"funnel">("reports");
  const[definitions,setDefinitions]=useState<LiveReportDefinition[]>([]);
  const[summary,setSummary]=useState<Record<string,number>>({});
  const[funnel,setFunnel]=useState<FunnelStage[]>([]);
  const[selectedReport,setSelectedReport]=useState<LiveReportResult|null>(null);
  const[loading,setLoading]=useState(true);
  const[reportLoading,setReportLoading]=useState("");
  const[error,setError]=useState("");
  const[search,setSearch]=useState("");

  const load=async()=>{try{setLoading(true);setError("");const[defs,liveSummary,liveFunnel]=await Promise.all([AnalyticsReportService.getDefinitions(),AnalyticsReportService.getSummary(),AnalyticsReportService.getFunnel()]);setDefinitions(defs);setSummary(liveSummary);setFunnel(liveFunnel)}catch(reason){setError(reason instanceof Error?reason.message:"Reports could not be loaded.")}finally{setLoading(false)}};
  useEffect(()=>{let active=true;Promise.all([AnalyticsReportService.getDefinitions(),AnalyticsReportService.getSummary(),AnalyticsReportService.getFunnel()]).then(([defs,liveSummary,liveFunnel])=>{if(!active)return;setDefinitions(defs);setSummary(liveSummary);setFunnel(liveFunnel)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Reports could not be loaded.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const filtered=useMemo(()=>definitions.filter(item=>`${item.name} ${item.category} ${item.description}`.toLowerCase().includes(search.toLowerCase())),[definitions,search]);
  const runReport=async(definition:LiveReportDefinition)=>{try{setReportLoading(definition.key);setError("");setSelectedReport(await AnalyticsReportService.run(definition.key))}catch(reason){setError(reason instanceof Error?reason.message:"The report could not be generated.")}finally{setReportLoading("")}};
  const baseline=funnel[0]?.count??0;
  const metrics=[{label:"Active leads",value:summary.leads??0,note:"Current non-converted enquiries",icon:TrendingUp,tone:"blue"},{label:"Registered students",value:summary.students??0,note:"Live student records",icon:Users,tone:"green"},{label:"Offer-stage cases",value:summary.offers??0,note:"Offers through enrolment",icon:FileSpreadsheet,tone:"amber"},{label:"Visa success",value:`${summary.visaRatio??0}%`,note:"Approved versus decided visas",icon:ShieldCheck,tone:"purple"}];
  return <div className="page-container live-reports-workspace">
    <div className="page-header-row"><div className="page-header-titles"><h2>{activeTab==="employees"?"Employee Reports":"Live CRM Reports & Analytics"}</h2><p>{activeTab==="employees"?"Monthly workforce intelligence for authorized HR and management decisions.":"Every figure below is calculated from current AECS records—no demo totals or prefilled pipeline values."}</p></div><div className="page-header-actions"><button type="button" className="btn-secondary" onClick={()=>void load()} disabled={loading}><RefreshCw size={15} className={loading?"spin":""}/>Refresh live data</button></div></div>
    {error&&<div className="employee-report-error"><AlertTriangle size={17}/><div><strong>Live reporting error</strong><span>{error}</span></div><button type="button" onClick={()=>void load()}>Retry</button></div>}
    {activeTab!=="employees"&&<div className="metrics-grid-4">{metrics.map(({label,value,note,icon:Icon,tone})=><article className="metric-box" key={label}><div className="metric-header"><span className="metric-label">{label}</span><span className={`metric-icon-wrap ${tone}`}><Icon size={17}/></span></div><div className="metric-value">{loading?"—":value}</div><span className="metric-sub">{note}</span></article>)}</div>}
    <div className="document-tabs"><button className={activeTab==="reports"?"active":""} onClick={()=>setActiveTab("reports")}><FileSpreadsheet size={16}/><span>Live Operational Reports</span></button><button className={activeTab==="employees"?"active":""} onClick={()=>setActiveTab("employees")}><Users size={16}/><span>Monthly Employee Report</span></button><button className={activeTab==="funnel"?"active":""} onClick={()=>setActiveTab("funnel")}><BarChart3 size={16}/><span>Live Student Pipeline</span></button></div>
    {activeTab==="employees"?<EmployeeMonthlyReport/>:activeTab==="reports"?<section className="live-report-panel"><header><div><h3>Operational report centre</h3><p>Generate a report from its authorized database view, inspect the actual rows, then export them.</p></div><label><Search size={15}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search live reports"/></label></header><div className="live-report-grid">{filtered.map(definition=><article key={definition.key}><span>{definition.category}</span><h4>{definition.name}</h4><p>{definition.description}</p><footer><small>Live database view</small><button type="button" className="btn-primary" disabled={reportLoading===definition.key} onClick={()=>void runReport(definition)}>{reportLoading===definition.key?<RefreshCw size={14} className="spin"/>:<Eye size={14}/>}Generate report</button></footer></article>)}{!loading&&!filtered.length&&<div className="live-report-empty"><FileSpreadsheet size={28}/><strong>No authorized reports found</strong><span>Your role may not have access, or the report catalog has not been configured.</span></div>}</div></section>:<section className="live-funnel-panel"><header><div><h3>AECS live student lifecycle</h3><p>Current totals calculated directly from leads, counselling, applications, and visa records.</p></div><span>{baseline.toLocaleString()} source leads</span></header><div className="live-funnel-list">{funnel.map((stage,index)=>{const pct=baseline?Math.min(100,Math.round(stage.count/baseline*100)):0;return <article key={stage.key}><div><span>Stage {index+1}</span><strong>{stage.label}</strong><em>{stage.count.toLocaleString()} records</em><b>{pct}%</b></div><i><span style={{width:`${pct}%`,background:stage.color}}/></i><p>{stage.note}</p></article>})}{!loading&&!funnel.some(stage=>stage.count>0)&&<div className="live-funnel-empty"><BarChart3 size={28}/><strong>No pipeline records yet</strong><span>The pipeline will populate automatically as real leads and applications are recorded.</span></div>}</div></section>}
    {selectedReport&&<div className="modal-backdrop-clean" onClick={()=>setSelectedReport(null)}><div className="modal-dialog-clean live-report-modal" onClick={event=>event.stopPropagation()}><div className="modal-header-clean"><div><span className="live-report-eyebrow">Generated from live CRM data</span><h3>{selectedReport.name}</h3><p>{selectedReport.rows.length} current database {selectedReport.rows.length===1?"row":"rows"}</p></div><button type="button" className="drawer-close-btn" onClick={()=>setSelectedReport(null)}><X size={18}/></button></div><div className="live-report-table-wrap">{selectedReport.rows.length?<table className="crm-table"><thead><tr>{Object.keys(selectedReport.rows[0]).map(key=><th key={key}>{pretty(key)}</th>)}</tr></thead><tbody>{selectedReport.rows.map((row,index)=><tr key={index}>{Object.keys(selectedReport.rows[0]).map(key=><td key={key}>{displayValue(row[key])}</td>)}</tr>)}</tbody></table>:<div className="live-report-empty"><FileSpreadsheet size={28}/><strong>No records found</strong><span>This is a valid live result. Add CRM records and run the report again.</span></div>}</div><div className="modal-footer-clean"><button type="button" className="btn-secondary" onClick={()=>setSelectedReport(null)}>Close</button><button type="button" className="btn-primary" disabled={!selectedReport.rows.length} onClick={()=>downloadReport(selectedReport)}><Download size={15}/>Export actual rows (CSV)</button></div></div></div>}
  </div>
}

export default AnalyticsDashboard;
