export type ReportGroup = "CRM & Consultancy" | "Accounting & Finance" | "Control & Intelligence";

export interface ReportCategory {
  id: number;
  group: ReportGroup;
  name: string;
  description: string;
  reports: string[];
}

const list = (value: string) => value.split("|").map(item => item.trim()).filter(Boolean);
const category = (id: number, group: ReportGroup, name: string, description: string, reports: string): ReportCategory => ({ id, group, name, description, reports: list(reports) });

export const REPORT_CATALOGUE: ReportCategory[] = [
  category(1,"CRM & Consultancy","Dashboard & Executive Reports","Executive KPIs, growth, revenue, branch and department visibility.","Executive Summary|Financial Dashboard|Business Overview|Branch Performance|KPI Dashboard|Department Performance|Revenue & Collection Dashboard|Business Growth Analysis|Student & Application Dashboard|Year-over-Year Comparison|Visa Performance Dashboard|Month-over-Month Comparison|HR Dashboard"),
  category(2,"CRM & Consultancy","Daily Management Reports","Daily operational activity and pending-work control.","Daily Business Summary|Daily Class Registration|Daily Lead Report|Daily Sales|Daily Enquiry Report|Daily Payment Collection|Daily Student Registration|Daily Expense|Daily Counselling Report|Daily Attendance|Daily Application Report|Daily Follow-up|Daily Visa Activity|Daily Pending Work|Daily Test Booking"),
  category(3,"CRM & Consultancy","Leads & Enquiries Reports","Lead ownership, conversion, source, follow-up and aging.","Lead Summary|Lost Lead|Enquiry Summary|Lost Lead Reason|Lead Master|Follow-up Required|Lead Source|Follow-up History|Lead Status|Overdue Follow-up|Lead Conversion|Lead Aging|Lead Conversion by Employee|Unassigned Lead|Lead Conversion by Source|Duplicate Lead|Lead Conversion by Destination"),
  category(4,"CRM & Consultancy","Student Reports","Student master data, ownership, status, source and pipeline.","Student Master|Student Counsellor|New Students|Student Source|Active Students|Student Document|Inactive Students|Student Profile|Student Status|Student Registration|Student Destination|Student Conversion|Student Intake|Student Pipeline|Student Service"),
  category(5,"CRM & Consultancy","Student Journey & Pipeline Reports","End-to-end conversion, aging, bottlenecks and drop-off.","Student Journey Summary|Acceptance to Visa Conversion|Student Pipeline|Visa to Enrolment Conversion|Enquiry to Counselling Conversion|End-to-End Student Conversion|Counselling to Application Conversion|Student Drop-off Analysis|Application to Offer Conversion|Student Journey Aging|Offer to Acceptance Conversion|Students Stuck in Pipeline"),
  category(6,"CRM & Consultancy","Counselling Reports","Counselling activity, follow-up, outcomes and productivity.","Counselling Summary|Counselling Conversion|Daily Counselling|Counselling by Destination|Counselling History|Counselling by Course|Counselling Follow-up|Counselling by Source|Pending Follow-up|Counselling Outcome|Counsellor Performance|Counselling Productivity"),
  category(7,"CRM & Consultancy","Application Reports","Application pipeline, aging, outcome and officer performance.","Application Summary|Application Aging|Application Master|Application Outcome|Application Status|Application by Country|New Applications|Application by Institution|Submitted Applications|Application by Course|Pending Applications|Application by Intake|Pending Documents|Application Officer Performance|Offer Letter|Application Conversion|Offer Acceptance"),
  category(8,"CRM & Consultancy","Institution & Course Reports","Institution, course, country and intake performance.","Institution Summary|Course Performance|Institution Master|Course-wise Applications|Institution Performance|Course-wise Students|Institution-wise Applications|Intake Summary|Institution-wise Offers|Intake-wise Applications|Institution-wise Visa|Country-wise Institutions|Course Summary|Country-wise Courses|Course Master"),
  category(9,"CRM & Consultancy","Offer & Admission Reports","Offer stages, acceptance, expiry and admission conversion.","Offer Letter Summary|Offer Rejection|Conditional Offer|Offer Expiry|Unconditional Offer|Offer-to-Enrolment Conversion|Offer Pending|Institution Admission Performance|Offer Acceptance"),
  category(10,"CRM & Consultancy","Visa Reports","Visa submissions, outcomes, success rates and processing.","Visa Application Summary|Visa Processing Time|Visa Master|Visa by Country|Visa Status|Visa by Institution|Visa Submitted|Visa by Course|Visa Granted|Visa by Intake|Visa Refused|Visa Officer Performance|Visa Withdrawn|Visa Outcome Analysis|Visa Success Rate|Pending Visa|Visa Refusal Rate"),
  category(11,"CRM & Consultancy","Test Booking Reports","Test bookings, schedules, sales, payment and outcomes.","Test Booking Summary|Exam Date|Test Booking Master|Upcoming Tests|IELTS Booking|Completed Tests|PTE Booking|Reschedule|Duolingo Booking|Cancellation|Test-wise Sales|Refund|Test-wise Payment|Test Booking Sales|Test Centre|Test Booking Outstanding"),
  category(12,"CRM & Consultancy","Class & Training Reports","Class, batch, attendance, completion and performance.","Class Registration|Instructor Performance|Active Classes|Class Payment|Completed Classes|Class Outstanding|Batch Summary|Class Performance|Batch-wise Students|Upcoming Classes|Class Attendance|Class Completion|Student Attendance|Student Training History"),
  category(13,"CRM & Consultancy","Services & Package Reports","Service/package sales, utilization, revenue and outstanding.","Service Master|Package-wise Students|Service Sales|Active Packages|Service-wise Revenue|Expired Packages|Service-wise Students|Package Utilization|Package Master|Service Conversion|Package Sales|Service Outstanding|Package-wise Revenue"),
  category(14,"CRM & Consultancy","Document & Workflow Reports","Document completeness, verification, aging and workflow.","Student Document Checklist|Document Resubmission|Missing Documents|Application Document Status|Pending Verification|Visa Document Status|Document Submission Aging|Document Collection Performance|Document Verification|Workflow Pending Items|Document Rejection|Workflow Aging"),
  category(15,"CRM & Consultancy","Destination & Country Intelligence Reports","Country demand, outcomes, revenue and growth.","Country-wise Student Demand|Country-wise Revenue|Country-wise Applications|Country-wise Conversion|Country-wise Offers|Country-wise Refusal|Country-wise Visa|Country-wise Intake Trend|Country-wise Visa Success|Destination Growth Analysis"),
  category(16,"CRM & Consultancy","Intake & Admission Planning Reports","Intake demand, applications, offers, visas and capacity.","Intake Summary|Intake-wise Visa|Upcoming Intake|Intake-wise Revenue|Intake-wise Student Demand|Intake Conversion|Intake-wise Applications|Intake Capacity vs Applications|Intake-wise Offers"),
  category(17,"CRM & Consultancy","Referral & Partner Reports","Referral, B2B partner, commission and revenue performance.","Referral Source Summary|Partner-wise Applications|Referral Students|Partner-wise Visa Success|Referral Conversion|Partner-wise Revenue|Referral Revenue|Commission Payable|Referral Commission|Commission Paid|Partner Performance|Commission Outstanding"),
  category(18,"CRM & Consultancy","University / Institution Relationship Reports","Institution volumes, outcomes, processing time and ranking.","Institution Application Volume|Institution Processing Time|Institution Offer Rate|Institution-wise Students|Institution Acceptance Rate|Institution Performance Ranking|Institution Visa Success|Institution Intake Performance|Institution Revenue"),
  category(19,"CRM & Consultancy","Communication Reports","Calls, messages, email, response and employee activity.","Communication Summary|Communication by Employee|Student Communication History|Follow-up Communication|Call Log|Unanswered Communication|WhatsApp Communication|Communication Response Rate|Email Communication|Communication Activity|SMS Communication"),
  category(20,"CRM & Consultancy","Marketing Reports","Lead sources, campaigns, social channels, cost and ROI.","Marketing Summary|Instagram Leads|Lead Source Performance|Website Leads|Campaign Performance|Referral Report|Campaign Conversion|Referral Conversion|Campaign Cost|Content Performance|Marketing ROI|Advertisement Performance|Social Media Enquiries|Marketing Revenue|Facebook Leads"),
  category(21,"CRM & Consultancy","Student Retention & Re-engagement Reports","Inactive/lost students, returning service and re-engagement.","Inactive Student|Repeat Service|Lost Student|Student Retention Rate|Dormant Lead|Lost Student Reason|Re-engagement|Re-engagement Conversion|Returning Student"),
  category(22,"CRM & Consultancy","Sales Reports","Sales totals, ownership, targets, growth and cancellation.","Sales Summary|Sales by Department|Daily Sales|Sales by Country|Monthly Sales|Sales by Student|Yearly Sales|Sales Target|Sales by Service|Sales Achievement|Sales by Package|Sales Growth|Sales by Employee|Discounted Sales|Sales by Branch|Cancelled Sales"),
  category(23,"CRM & Consultancy","Payment & Collection Reports","Collections, methods, outstanding balances and aging.","Payment Summary|Bank Payment|Daily Collection|Online Payment|Monthly Collection|QR Payment|Payment Master|Collection Target|Payment by Student|Collection Achievement|Payment by Service|Outstanding Payment|Payment by Employee|Overdue Payment|Payment Method|Receivable Aging|Cash Payment|Refund"),
  category(24,"CRM & Consultancy","Commission & Incentive Reports","Employee, counselling, sales, application and visa incentives.","Employee Commission|Commission Calculation|Counsellor Incentive|Commission Payable|Sales Incentive|Commission Paid|Application Incentive|Incentive Outstanding|Visa Incentive|Employee Incentive Summary|Booking Incentive"),
  category(25,"CRM & Consultancy","Operational Productivity Reports","Tasks, workload, productivity, processing time and SLA.","Employee Activity|Pending Tasks|Counsellor Productivity|Overdue Tasks|Application Officer Productivity|Employee Workload|Visa Officer Productivity|Department Workload|Follow-up Productivity|Average Processing Time|Tasks Completed|SLA Breach"),
  category(37,"Accounting & Finance","Accounting Reports","Accounting configuration, periods, transactions and dimensions.","Accounting Summary|Financial Year|Accounting Dashboard|Accounting Transaction Summary|Chart of Accounts|Branch-wise Accounting|Account Master|Department-wise Accounting|Accounting Period|Cost Centre"),
  category(38,"Accounting & Finance","Cash & Bank Reports","Cash/bank books, receipts, payments and reconciliation.","Cash Book|Cash Payments|Bank Book|Bank Receipts|Cash Summary|Bank Payments|Bank Summary|Bank Reconciliation|Cash Transactions|Unreconciled Transactions|Bank Transactions|Cash Position|Cash Receipts|Bank Position"),
  category(39,"Accounting & Finance","Accounts Receivable Reports","Student/customer receivables, aging, collection and ledgers.","Accounts Receivable Summary|Collection Follow-up|Customer/Student Receivable|Receivable by Service|Invoice Receivable|Receivable by Employee|Outstanding Receivable|Receivable by Branch|Receivable Aging|Receivable Statement|Overdue Receivable|Customer/Student Ledger"),
  category(40,"Accounting & Finance","Accounts Payable Reports","Vendor payables, aging, due payments and ledgers.","Accounts Payable Summary|Vendor Payment|Vendor Payable|Payable by Category|Outstanding Payable|Payable by Branch|Payable Aging|Payable Statement|Overdue Payable|Payment Due|Vendor Ledger"),
  category(41,"Accounting & Finance","Income Reports","Income by period, category, service, branch and employee.","Income Summary|Income by Branch|Daily Income|Income by Department|Monthly Income|Income by Employee|Yearly Income|Student/Customer Income|Income by Category|Income Growth|Income by Service|Income Comparison"),
  category(42,"Accounting & Finance","Expense Reports","Expense period, category, vendor, approval and trends.","Expense Summary|Expense by Employee|Daily Expense|Vendor Expense|Monthly Expense|Recurring Expense|Yearly Expense|Expense Approval|Expense by Category|Expense Trend|Expense by Branch|Expense Comparison|Expense by Department"),
  category(43,"Accounting & Finance","Journal & Ledger Reports","Journals, account ledgers, adjustments and audit.","Journal Entry|Bank Ledger|Journal Summary|Journal by Account|General Ledger|Journal by Date|Account Ledger|Journal by Branch|Customer/Student Ledger|Journal Adjustment|Vendor Ledger|Journal Audit|Cash Ledger"),
  category(44,"Accounting & Finance","Trial Balance Reports","Opening, monthly, yearly, adjusted and comparative trial balances.","Trial Balance|Department-wise Trial Balance|Opening Trial Balance|Trial Balance Comparison|Monthly Trial Balance|Debit/Credit Summary|Yearly Trial Balance|Adjusted Trial Balance|Branch-wise Trial Balance|Closing Trial Balance"),
  category(45,"Accounting & Finance","Profit & Loss Reports","Profit/loss statements, margins, trends and comparisons.","Profit & Loss Statement|Comparative Profit & Loss|Monthly Profit & Loss|Gross Profit|Yearly Profit & Loss|Net Profit|Branch-wise Profit & Loss|Profit Margin|Department-wise Profit & Loss|Profit Trend|Service-wise Profit & Loss"),
  category(46,"Accounting & Finance","Balance Sheet Reports","Assets, liabilities, equity, net worth and comparisons.","Balance Sheet|Liabilities Summary|Monthly Balance Sheet|Equity Summary|Yearly Balance Sheet|Current Assets|Branch-wise Balance Sheet|Current Liabilities|Comparative Balance Sheet|Net Worth|Assets Summary"),
  category(47,"Accounting & Finance","Cash Flow Reports","Operating, investing and financing cash flow over time.","Cash Flow Statement|Financing Cash Flow|Daily Cash Flow|Cash Inflow|Monthly Cash Flow|Cash Outflow|Yearly Cash Flow|Net Cash Flow|Operating Cash Flow|Cash Flow Comparison|Investing Cash Flow"),
  category(48,"Accounting & Finance","Budget & Variance Reports","Budgets, actuals, utilization and variance analysis.","Budget Summary|Service Budget|Budget vs Actual|Monthly Budget Variance|Revenue Budget vs Actual|Annual Budget Variance|Expense Budget vs Actual|Variance Analysis|Department Budget|Budget Utilization|Branch Budget|Budget Achievement"),
  category(49,"Accounting & Finance","Tax & VAT Reports","VAT/TDS transactions, liability, payment and reconciliation.","VAT Summary|TDS Summary|VAT Sales|TDS Deduction|VAT Purchase|TDS Payment|VAT Payable|Tax Liability|VAT Receivable|Tax Payment|VAT Transactions|Tax Reconciliation|VAT Return"),
  category(50,"Accounting & Finance","Asset Reports","Asset register, purchase, allocation, depreciation and disposal.","Asset Master|Asset Location|Asset Register|Asset Depreciation|Asset Category|Asset Transfer|Asset Purchase|Asset Maintenance|Asset Allocation|Asset Disposal|Employee-wise Asset|Asset Status|Branch-wise Asset|Asset Value"),
  category(51,"Accounting & Finance","Financial Statement Reports","Formal statements, equity, ratios and comparisons.","Income Statement|Comparative Financial Statements|Profit & Loss Statement|Monthly Financial Statements|Balance Sheet|Annual Financial Statements|Cash Flow Statement|Branch-wise Financial Statements|Trial Balance|Department-wise Financial Statements|Statement of Changes in Equity|Financial Ratio Report"),
  category(52,"Control & Intelligence","Compliance Reports","Student, application, employee, tax and document compliance.","Student Document Compliance|VAT Compliance|Application Compliance|Agreement & Consent|Employee Compliance|Expired Documents|HR Compliance|Upcoming Expiry|Financial Compliance|Missing Documents|Tax Compliance|Compliance Status Summary"),
  category(53,"Control & Intelligence","Audit & System Reports","User, security, approval, modification and export history.","Audit Trail|Payment Modification Log|User Activity Log|Accounting Modification Log|Login History|Payroll Modification Log|Modification Log|Report Export History|Deleted Record Log|Security Activity|Approval History|System Error Log|Email Communication Log"),
  category(54,"Control & Intelligence","Consultancy Analytics & Intelligence Reports","Funnels, profitability, forecasts, trends, rankings and alerts.","Lead Funnel Analysis|Customer Acquisition Cost|Student Funnel Analysis|Lead-to-Revenue Analysis|Application Funnel|Service Profitability|Visa Funnel|Destination Profitability|Sales Funnel|Institution Profitability|Conversion Funnel|Forecast Report|Bottleneck Analysis|Business Trend Analysis|Processing Time Analysis|Performance Ranking|Staff Productivity Analysis|Exception Report|Revenue per Student|Management Alerts|Revenue per Lead"),
  category(55,"Control & Intelligence","Custom Reports","Configurable, saved, shared, scheduled and favourite reports.","Report Builder|Saved Reports|Custom CRM Reports|Shared Reports|Custom Accounting Reports|Scheduled Reports|Custom Sales Reports|Report Templates|Custom Finance Reports|Export History|Report Favorites"),
];

export const REPORT_COUNT = REPORT_CATALOGUE.reduce((total, item) => total + item.reports.length, 0);
export const reportKey = (categoryId: number, name: string) => `${categoryId}-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`;
