-- Phase 5: class operations, enrolment, attendance, mock tests and progress.
create sequence public.class_student_number_seq;
create table public.class_students(
 id uuid primary key default gen_random_uuid(),student_code text not null unique,linked_student_id uuid references public.students(id),full_name text not null,phone text not null,alt_phone text,email citext,gender text,education_level text,guardian_name text,guardian_phone text,address text,record_status text not null default 'Active',notes text,created_by uuid not null references public.staff_profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
alter table public.batch_enrollments alter column student_id drop not null;
alter table public.batch_enrollments add column class_student_id uuid references public.class_students(id) on delete cascade;
alter table public.batch_enrollments add column mode text not null default 'Classroom' check(mode in('Classroom','Online','Hybrid'));
alter table public.batch_enrollments add column expected_completion date;
alter table public.batch_enrollments add column status text not null default 'Active' check(status in('Active','Completed','Transferred','On Hold'));
alter table public.batch_enrollments add column notes text;
alter table public.batch_enrollments add constraint enrolment_student_source check((student_id is not null)::int+(class_student_id is not null)::int=1);
create unique index batch_enrolment_class_student_unique on public.batch_enrollments(batch_id,class_student_id) where class_student_id is not null;

create table public.attendance_sessions(id uuid primary key default gen_random_uuid(),batch_id uuid not null references public.test_prep_batches(id) on delete cascade,session_date date not null,topic text,recorded_by uuid not null references public.staff_profiles(id),created_at timestamptz not null default now(),unique(batch_id,session_date));
create table public.attendance_records(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.attendance_sessions(id) on delete cascade,enrolment_id uuid not null references public.batch_enrollments(id) on delete cascade,status text not null check(status in('PRESENT','ABSENT','LATE','EXCUSED')),remarks text,marked_by uuid not null references public.staff_profiles(id),marked_at timestamptz not null default now(),unique(session_id,enrolment_id));

create sequence public.mock_test_number_seq;
create table public.mock_test_slots(id uuid primary key default gen_random_uuid(),title text not null,test_type text not null,test_date date not null,test_time time not null,room text not null,invigilator text not null,total_seats integer not null check(total_seats>0),status text not null default 'OPEN' check(status in('OPEN','FULL','COMPLETED')),created_by uuid not null references public.staff_profiles(id),created_at timestamptz not null default now());
create table public.mock_test_results(id uuid primary key default gen_random_uuid(),test_code text not null unique,class_student_id uuid not null references public.class_students(id) on delete cascade,slot_id uuid references public.mock_test_slots(id),test_type text not null,test_date date not null,venue text not null,examiner text not null,listening numeric,reading numeric,writing numeric,speaking numeric,overall_score text,status text not null check(status in('Score Issued','Pending Evaluation','Absent','Scheduled')),examiner_feedback text,target_achieved boolean not null default false,created_by uuid not null references public.staff_profiles(id),created_at timestamptz not null default now());

insert into public.permissions(role,permission_name,enabled)
select role,permission_name,true from (values('ADMIN'::public.staff_role),('DIRECTOR'),('FACULTY'))r(role) cross join(values('classes.view'),('classes.manage'),('attendance.manage'),('mocks.manage'))p(permission_name)
on conflict(role,permission_name)do update set enabled=excluded.enabled;
insert into public.permissions(role,permission_name,enabled) select role,'classes.view',true from(values('SENIOR_COUNSELLOR'::public.staff_role),('COUNSELLOR'),('FRONT_DESK'))r(role) on conflict(role,permission_name)do update set enabled=excluded.enabled;

do $$ declare t text;begin foreach t in array array['class_students','attendance_sessions','attendance_records','mock_test_slots','mock_test_results'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
drop policy if exists staff_batches_policy on public.test_prep_batches;drop policy if exists staff_enrollments_policy on public.batch_enrollments;
create policy batches_read on public.test_prep_batches for select to authenticated using(public.has_permission('classes.view'));
create policy enrolments_read on public.batch_enrollments for select to authenticated using(public.has_permission('classes.view'));
do $$ declare t text;begin foreach t in array array['class_students','attendance_sessions','attendance_records','mock_test_slots','mock_test_results'] loop execute format('create policy %I_read on public.%I for select to authenticated using(public.has_permission(''classes.view''))',t,t);end loop;end$$;
create policy class_students_manage on public.class_students for all to authenticated using(public.has_permission('classes.manage')) with check(public.has_permission('classes.manage'));

create or replace function public.create_class_student(payload jsonb)returns jsonb language plpgsql security definer set search_path=public as $$declare sid uuid;bid uuid;eid uuid;code text;begin if not public.has_permission('classes.manage')then raise exception'Insufficient permission';end if;select id into bid from test_prep_batches where batch_code=payload->>'batch_code';if bid is null then raise exception'Batch not found';end if;code:='CLS-'||to_char(now(),'YYYY')||'-'||lpad(nextval('class_student_number_seq')::text,4,'0');insert into class_students(student_code,full_name,phone,alt_phone,email,gender,education_level,guardian_name,guardian_phone,address,record_status,notes,created_by)values(code,payload->>'full_name',payload->>'phone',nullif(payload->>'alt_phone',''),nullif(payload->>'email',''),payload->>'gender',payload->>'education_level',payload->>'guardian_name',payload->>'guardian_phone',payload->>'address',payload->>'record_status',payload->>'notes',auth.uid())returning id into sid;insert into batch_enrollments(batch_id,class_student_id,mode,expected_completion,status,notes)values(bid,sid,payload->>'mode',nullif(payload->>'expected_completion','')::date,payload->>'class_status',payload->>'enrolment_notes')returning id into eid;return jsonb_build_object('id',sid,'student_code',code,'enrolment_id',eid);end$$;
create or replace function public.create_test_batch(payload jsonb)returns uuid language plpgsql security definer set search_path=public as $$declare bid uuid;begin if not public.has_permission('classes.manage')then raise exception'Insufficient permission';end if;insert into test_prep_batches(batch_code,course_type,title,timing,room,instructor_name,max_capacity,start_date,status)values(payload->>'batch_code',(payload->>'course_type')::batch_course_type,payload->>'title',payload->>'timing',payload->>'room',payload->>'instructor',(payload->>'max_capacity')::integer,(payload->>'start_date')::date,(payload->>'status')::batch_status)returning id into bid;return bid;end$$;
create or replace function public.create_mock_slot(payload jsonb)returns uuid language plpgsql security definer set search_path=public as $$declare rid uuid;begin if not public.has_permission('mocks.manage')then raise exception'Insufficient permission';end if;insert into mock_test_slots(title,test_type,test_date,test_time,room,invigilator,total_seats,status,created_by)values(payload->>'title',payload->>'test_type',(payload->>'date')::date,(payload->>'time')::time,payload->>'room',payload->>'invigilator',(payload->>'total_seats')::integer,payload->>'status',auth.uid())returning id into rid;return rid;end$$;
create or replace function public.create_mock_result(payload jsonb)returns uuid language plpgsql security definer set search_path=public as $$declare sid uuid;rid uuid;code text;begin if not public.has_permission('mocks.manage')then raise exception'Insufficient permission';end if;select id into sid from class_students where student_code=payload->>'student_code';if sid is null then raise exception'Class student not found';end if;code:='MOCK-'||to_char(now(),'YYYY')||'-'||lpad(nextval('mock_test_number_seq')::text,5,'0');insert into mock_test_results(test_code,class_student_id,test_type,test_date,venue,examiner,listening,reading,writing,speaking,overall_score,status,examiner_feedback,target_achieved,created_by)values(code,sid,payload->>'test_type',(payload->>'test_date')::date,payload->>'venue',payload->>'examiner',nullif(payload->>'listening','')::numeric,nullif(payload->>'reading','')::numeric,nullif(payload->>'writing','')::numeric,nullif(payload->>'speaking','')::numeric,payload->>'overall_score',payload->>'status',payload->>'examiner_feedback',(payload->>'target_achieved')::boolean,auth.uid())returning id into rid;return rid;end$$;
create or replace function public.mark_class_attendance(class_student_uuid uuid,attendance_date date,attendance_status text)returns void language plpgsql security definer set search_path=public as $$declare enrol record;session_uuid uuid;begin if not public.has_permission('attendance.manage')then raise exception'Insufficient permission';end if;if attendance_status not in('PRESENT','ABSENT','LATE','EXCUSED')then raise exception'Invalid attendance status';end if;select id,batch_id into enrol from batch_enrollments where class_student_id=class_student_uuid and status='Active'limit 1;if enrol.id is null then raise exception'Active enrolment not found';end if;insert into attendance_sessions(batch_id,session_date,recorded_by)values(enrol.batch_id,attendance_date,auth.uid())on conflict(batch_id,session_date)do update set recorded_by=excluded.recorded_by returning id into session_uuid;insert into attendance_records(session_id,enrolment_id,status,marked_by)values(session_uuid,enrol.id,attendance_status,auth.uid())on conflict(session_id,enrolment_id)do update set status=excluded.status,marked_by=excluded.marked_by,marked_at=now();end$$;
revoke all on function public.create_class_student(jsonb),public.create_test_batch(jsonb),public.create_mock_slot(jsonb),public.create_mock_result(jsonb),public.mark_class_attendance(uuid,date,text)from public;grant execute on function public.create_class_student(jsonb),public.create_test_batch(jsonb),public.create_mock_slot(jsonb),public.create_mock_result(jsonb),public.mark_class_attendance(uuid,date,text)to authenticated;
