-- Phase 10: production health, client error telemetry and backup verification evidence.
create table public.system_health_events(id bigint generated always as identity primary key,severity text not null check(severity in('INFO','WARNING','ERROR','CRITICAL')),component text not null,message text not null,context jsonb not null default'{}',staff_id uuid references public.staff_profiles(id),created_at timestamptz not null default now());
create table public.backup_verifications(id uuid primary key default gen_random_uuid(),backup_type text not null check(backup_type in('AUTOMATED','MANUAL','RESTORE_DRILL')),provider text not null,backup_reference text not null unique,started_at timestamptz not null,completed_at timestamptz,status text not null check(status in('STARTED','VERIFIED','FAILED')),verified_by uuid references public.staff_profiles(id),notes text,created_at timestamptz not null default now());
create index system_health_events_created_idx on public.system_health_events(severity,created_at desc);create index backup_verifications_created_idx on public.backup_verifications(created_at desc);
insert into public.permissions(role,permission_name,enabled)select role,permission_name,true from(values('ADMIN'::public.staff_role),('DIRECTOR'),('IT_ADMIN'))r(role)cross join(values('monitoring.view'),('monitoring.manage'),('backups.verify'))p(permission_name)on conflict(role,permission_name)do update set enabled=true;
alter table public.system_health_events enable row level security;alter table public.backup_verifications enable row level security;
create policy monitoring_admin_read on public.system_health_events for select to authenticated using(public.has_permission('monitoring.view'));create policy backups_admin_read on public.backup_verifications for select to authenticated using(public.has_permission('monitoring.view'));create policy backups_admin_write on public.backup_verifications for all to authenticated using(public.has_permission('backups.verify'))with check(public.has_permission('backups.verify'));
create or replace function public.record_client_error(error_message text,error_context jsonb default'{}')returns void language plpgsql security definer set search_path=public as $$begin if auth.uid()is null then return;end if;insert into system_health_events(severity,component,message,context,staff_id)values('ERROR','web-client',left(error_message,2000),coalesce(error_context,'{}'),auth.uid());end$$;
revoke all on function public.record_client_error(text,jsonb)from public;grant execute on function public.record_client_error(text,jsonb)to authenticated;
comment on table public.backup_verifications is'Backup metadata only. Database backups remain managed by the configured infrastructure provider.';
